const key='forma-cad-coil-presets-v1',fieldLabels={wire:'コイルの太さ',pitch:'ピッチ',turns:'巻き数',wall:'筒の厚さ',bodyBoreWall:'本体内穴の壁厚',jointGap:'かみ合わせのすき間',jointSeam:'合わせ目のすき間',closeAngle:'角度補正',latchGap:'固定部のすき間',latchEngagement:'固定部の掛かり量',stopFaceSetback:'回転止め面の引き込み量',filletRadius:'外側のフィレット半径',filletVerticalRadius:'縦角のフィレット半径',filletCapRadius:'端面のフィレット半径'};
export const coilPresetFields=['wire','pitch','turns','wall','bodyBoreWall','jointGap','jointSeam','hand','autoAdjust','alignStop','rimSeat','jointLatch','latchStyle','latchFirm','latchExtraFirm','latchGap','latchEngagement','stopFaceSetback','closeAngle','closeAngleZero','autoFillet','filletRadius','filletVerticalRadius','filletCapRadius','filletBodyBottom','filletLidTop','filletVertical'];
export function validateCoilPreset(values){
 const out={};for(const field of coilPresetFields){const value=values?.[field]===undefined?(field==='filletVerticalRadius'||field==='filletCapRadius'?values?.filletRadius??2:field==='filletRadius'?values?.filletCapRadius??values?.filletVerticalRadius??2:({bodyBoreWall:0,rimSeat:false,jointLatch:false,latchStyle:'claw',latchFirm:false,latchExtraFirm:false,closeAngleZero:0,autoFillet:false,filletRadius:2,filletBodyBottom:true,filletLidTop:true,filletVertical:true,latchGap:.3,latchEngagement:.8,stopFaceSetback:0}[field])):values?.[field];if(['autoAdjust','alignStop','rimSeat','jointLatch','latchFirm','latchExtraFirm','autoFillet','filletBodyBottom','filletLidTop','filletVertical'].includes(field)){if(typeof value!=='boolean')throw Error('チェック設定が不正です');}else if(field==='latchStyle'){if(!['claw','ridge'].includes(value))throw Error('固定形状が不正です');}else if(field==='closeAngleZero'){if(![-2,0,2].includes(value))throw Error('角度補正の基準が不正です');}else if(field==='hand'){if(!['右ねじ','左ねじ'].includes(value))throw Error('ねじの向きが不正です');}else{const min=field==='closeAngle'?-180:['filletRadius','filletVerticalRadius','filletCapRadius'].includes(field)?.05:field==='latchGap'?.05:field==='latchEngagement'?.4:field==='stopFaceSetback'?0:field==='turns'?1:field==='bodyBoreWall'?0:field==='jointGap'?.05:field==='jointSeam'?(values?.rimSeat===true||values?.jointLatch===true?0:.01):.1,max=field==='closeAngle'?180:['filletRadius','filletVerticalRadius','filletCapRadius'].includes(field)?10:field==='latchGap'?1:field==='latchEngagement'?1.6:field==='stopFaceSetback'?1:field==='turns'?30:10000;if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max||field==='turns'&&!Number.isInteger(value))throw Error('設定値が範囲外です：'+fieldLabels[field]);}if(field==='bodyBoreWall'&&value>0&&value<.6)throw Error('本体内穴の壁厚は0または0.6 mm以上で指定してください');out[field]=value;}if(out.jointLatch&&Math.abs(out.closeAngle)>10)throw Error('固定部付きの角度補正は−10〜10°で指定してください');if(out.latchExtraFirm&&!out.latchFirm)throw Error('爪の追加強化には腕と受け側の強化を有効にしてください');return out;
}
export function installCoilPresets(parent,{read,apply,storage=()=>window.localStorage}){
 const box=document.createElement('fieldset');box.id='coil-presets';box.innerHTML='<legend>印刷設定プリセット</legend><label>保存済みの設定<select id="coil-preset-select"><option value="">設定を選択</option></select></label><div class="coil-preset-actions"><button id="coil-preset-apply" type="button">呼び出す</button><button id="coil-preset-delete" type="button">削除</button></div><label>名前（プリンター・材料など）<input id="coil-preset-name" type="text" maxlength="60" placeholder="例：自宅プリンター・PLA"></label><button id="coil-preset-save" type="button">現在の設定を保存／同名を更新</button><p>入力したコイル寸法・すき間・ねじの向き・回転止め・縁で止める設定・固定方法・角度補正・自動フィレットを、このブラウザーに保存します。呼び出した後は現在のモデルで再計算します。</p><p id="coil-preset-status" role="status" aria-live="polite"></p>';
 parent.prepend(box);box.addEventListener('input',e=>e.stopPropagation());const el=id=>box.querySelector('#'+id),status=(message,error=false)=>{el('coil-preset-status').textContent=message;el('coil-preset-status').classList.toggle('error',error);};let presets=[];
 function refresh(selected=''){el('coil-preset-select').replaceChildren(new Option('設定を選択',''));for(const p of presets)el('coil-preset-select').add(new Option(p.name,p.name));el('coil-preset-select').value=selected;el('coil-preset-apply').disabled=el('coil-preset-delete').disabled=!selected;}
 try{const raw=storage().getItem(key);if(raw){const data=JSON.parse(raw);if(data.version!==1||!Array.isArray(data.presets)||data.presets.length>50)throw Error();const names=new Set();presets=data.presets.map(p=>{if(typeof p.name!=='string'||!p.name.trim()||p.name.length>60||names.has(p.name))throw Error();names.add(p.name);return {name:p.name,values:validateCoilPreset(p.values)};});}}catch{status('保存済みの設定を読み込めませんでした。コイル接合は通常どおり使用できます。',true);}refresh();
 function persist(next){storage().setItem(key,JSON.stringify({version:1,presets:next}));presets=next;}
 el('coil-preset-select').onchange=()=>{const name=el('coil-preset-select').value;el('coil-preset-name').value=name;refresh(name);status('');};
 el('coil-preset-save').onclick=()=>{try{const name=el('coil-preset-name').value.trim();if(!name||name.length>60)throw Error('名前を1〜60文字で入力してください');const values=validateCoilPreset(read()),next=presets.filter(p=>p.name!==name);if(next.length>=50)throw Error('保存できる設定は50件までです');next.push({name,values});try{persist(next);}catch{throw Error('このブラウザーに保存できませんでした。名前と入力値を残しています。');}refresh(name);status('「'+name+'」を保存しました');}catch(e){status(e.message,true);}};
 el('coil-preset-name').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing&&e.keyCode!==229){e.preventDefault();e.stopPropagation();el('coil-preset-save').click();}};
 el('coil-preset-apply').onclick=()=>{try{const preset=presets.find(p=>p.name===el('coil-preset-select').value);if(!preset)throw Error('設定を選択してください');apply(validateCoilPreset(preset.values));status('「'+preset.name+'」を呼び出しました。現在のモデルで再計算します。');}catch(e){status(e.message,true);}};
 el('coil-preset-delete').onclick=()=>{try{const name=el('coil-preset-select').value;if(!name)return;try{persist(presets.filter(p=>p.name!==name));}catch{throw Error('設定を削除できませんでした');}refresh();el('coil-preset-name').value='';status('「'+name+'」を削除しました');}catch(e){status(e.message,true);}};
 return box;
}
