import * as THREE from 'three';
import {sectionSegments} from './section-view.js';
import {draggablePanel} from './draggable-panel.js';
const ns='http://www.w3.org/2000/svg',format=v=>Number(v.toFixed(3)).toString(),svgNode=(tag,attrs={},text)=>{const el=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;};
// Fill closed cross sections using even/odd edge crossings. This also handles
// native mesh seams whose coincident vertices do not form degree-two loops.
export function sectionFillStrips(segments){
 const edges=[];for(let i=0;i<segments.length;i+=6){const a=[segments[i],segments[i+2]],b=[segments[i+3],segments[i+5]];if(Math.abs(a[1]-b[1])>1e-8)edges.push([a,b]);}const levels=edges.flatMap(e=>e.map(p=>p[1])).sort((a,b)=>a-b).filter((v,i,a)=>!i||Math.abs(v-a[i-1])>1e-7),fill=[],xAt=(edge,z)=>edge[0][0]+(edge[1][0]-edge[0][0])*(z-edge[0][1])/(edge[1][1]-edge[0][1]);
 const ordered=edges.map(edge=>({edge,min:Math.min(edge[0][1],edge[1][1]),max:Math.max(edge[0][1],edge[1][1])})).sort((a,b)=>a.min-b.min);let cursor=0,active=[];
 for(let i=1;i<levels.length;i++){const bottom=levels[i-1],top=levels[i],mid=(bottom+top)/2;while(cursor<ordered.length&&ordered[cursor].min<mid)active.push(ordered[cursor++]);active=active.filter(e=>e.max>mid);const crossings=active.map(e=>({edge:e.edge,x:xAt(e.edge,mid)})).sort((a,b)=>a.x-b.x).filter((v,j,a)=>!j||Math.abs(v.x-a[j-1].x)>1e-6);if(crossings.length%2)continue;for(let j=0;j<crossings.length;j+=2){const a=crossings[j].edge,b=crossings[j+1].edge,lo=[xAt(a,bottom),bottom],hi=[xAt(a,top),top],rightHi=[xAt(b,top),top],rightLo=[xAt(b,bottom),bottom];fill.push(lo,hi,rightHi,lo,rightHi,rightLo);}}
 return fill;
}
export function coilSectionData(outputs,q){
 const axis=new THREE.Vector3(...q.axis).normalize(),origin=new THREE.Vector3(...q.origin),rotation=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),axis).invert(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),parts=[],sectionAngle=.13,sectionRotation=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),-sectionAngle);
 for(const output of outputs){const vertices=[];for(let i=0;i<output.vertices.length;i+=3)vertices.push(...new THREE.Vector3(...output.vertices.slice(i,i+3)).sub(origin).applyQuaternion(rotation).applyQuaternion(sectionRotation).toArray());const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(output.triangles);try{const segments=sectionSegments(geometry,plane);parts.push({lid:output.id.endsWith('-lid'),segments,fill:sectionFillStrips(segments)});}finally{geometry.dispose();}}
 const low=q.split+q.seam+q.pilot+.03,high=q.split+q.neckLength-.03,phase=.5+(q.leftHand?-1:1)*sectionAngle/(2*Math.PI),candidate=(Math.ceil(low/q.pitch-phase)+phase)*q.pitch,gapZ=candidate<high?candidate:(low+high)/2,seamX=-(q.radius-Math.min(.25,q.wall/2));return {q,parts,gap:{a:[q.maleRadius,gapZ],b:[q.boreRadius,gapZ],value:q.gap},seam:{a:[seamX,q.split],b:[seamX,q.split+q.seam],value:q.seam}};
}
export function createCoilSection(parent,onRequest){
 const panel=document.createElement('section');panel.id='coil-section-panel';panel.hidden=true;panel.innerHTML='<button id="coil-section-close" type="button" aria-label="断面図を閉じる">×</button><p>閉じた状態の断面です。水色：本体、橙色：蓋。寸法は計算後の設定値（mm）です。</p><div class="coil-section-actions"><button type="button" data-coil-focus="all">全体</button><button type="button" data-coil-focus="gap">かみ合わせを拡大</button><button type="button" data-coil-focus="seam">合わせ目を拡大</button></div><p id="coil-section-status" role="status" aria-live="polite"></p><svg id="coil-section-svg" viewBox="0 0 680 460" role="img" aria-label="コイル接合の閉じた断面とすき間の寸法"></svg>';
 parent.append(panel);draggablePanel(panel,'すき間の断面図');let data=null,focus='all';const svg=panel.querySelector('svg'),status=panel.querySelector('#coil-section-status');
 function draw(){if(!data)return;const {q,parts,gap,seam}=data,W=680,H=460;svg.replaceChildren();const title=svgNode('title',{},'かみ合わせの片側すき間 '+format(q.gap)+' mm、合わせ目のすき間 '+format(q.seam)+' mm');svg.append(title);let bounds;
 if(focus==='all'){const points=parts.flatMap(p=>{const out=[];for(let i=0;i<p.segments.length;i+=3)out.push([p.segments[i],p.segments[i+2]]);return out;});bounds=[Math.min(...points.map(p=>p[0])),0,Math.max(...points.map(p=>p[0])),q.height];}else{const dimension=focus==='gap'?gap:seam,center=dimension.a.map((v,i)=>(v+dimension.b[i])/2),width=Math.max(3,q.wall*2.5,focus==='gap'?q.wire*3:q.seam*10),height=Math.max(3,focus==='gap'?q.pitch*1.6:q.seam*10);bounds=[center[0]-width/2,center[1]-height/2,center[0]+width/2,center[1]+height/2];}
 const scale=Math.min((W-100)/(bounds[2]-bounds[0]),(H-100)/(bounds[3]-bounds[1])),cx=(bounds[0]+bounds[2])/2,cz=(bounds[1]+bounds[3])/2,map=p=>[W/2+(p[0]-cx)*scale,H/2-(p[1]-cz)*scale],defs=svgNode('defs'),clip=svgNode('clipPath',{id:'coil-section-clip'});clip.append(svgNode('rect',{x:18,y:30,width:W-36,height:H-50}));defs.append(clip);svg.append(defs);const drawing=svgNode('g',{'clip-path':'url(#coil-section-clip)'});svg.append(drawing);
 for(const part of parts){const color=part.lid?'#b66a17':'#087f98',fill=part.lid?'#e4a34d':'#64aec5';let d='';for(let i=0;i<part.fill.length;i+=3)d+='M'+map(part.fill[i]).join(',')+'L'+map(part.fill[i+1]).join(',')+'L'+map(part.fill[i+2]).join(',')+'Z';if(d)drawing.append(svgNode('path',{d,fill,'fill-opacity':'.55','shape-rendering':'crispEdges'}));d='';for(let i=0;i<part.segments.length;i+=6)d+='M'+map([part.segments[i],part.segments[i+2]]).join(',')+'L'+map([part.segments[i+3],part.segments[i+5]]).join(',');drawing.append(svgNode('path',{d,fill:'none',stroke:color,'stroke-width':1.5}));}
 function dimension(d,label,color,vertical=false){const a=map(d.a),b=map(d.b),middle=a.map((v,i)=>(v+b[i])/2),line=(p,r)=>svg.append(svgNode('line',{x1:p[0],y1:p[1],x2:r[0],y2:r[1],stroke:color,'stroke-width':2}));line(a,b);for(const p of [a,b])line(vertical?[p[0]-7,p[1]]:[p[0],p[1]-7],vertical?[p[0]+7,p[1]]:[p[0],p[1]+7]);const labelX=vertical?Math.max(30,middle[0]-20):Math.min(W-30,middle[0]+155),labelY=vertical?Math.min(H-30,middle[1]+45):Math.max(62,middle[1]-45),anchor=vertical?'start':'end';line(middle,[labelX, labelY-8]);svg.append(svgNode('rect',{x:anchor==='start'?labelX-5:labelX-245,y:labelY-25,width:250,height:30,rx:4,fill:'white','fill-opacity':'.94'}));svg.append(svgNode('text',{x:labelX,y:labelY-5,'text-anchor':anchor,fill:color,'font-size':16,'font-weight':600},label+' '+format(d.value)+' mm'));}
 if(focus!=='seam')dimension(gap,'かみ合わせ（片側）','#0a6681');if(focus!=='gap')dimension(seam,'合わせ目','#96540c',true);panel.dataset.focus=focus;panel.dataset.gap=q.gap;panel.dataset.seam=q.seam;status.textContent='閉じた状態 / 軸を通る断面 / かみ合わせ '+format(q.gap)+' mm・片側 / 合わせ目 '+format(q.seam)+' mm';for(const button of panel.querySelectorAll('[data-coil-focus]'))button.setAttribute('aria-pressed',String(button.dataset.coilFocus===focus));
 }
 panel.querySelector('#coil-section-close').onclick=()=>{panel.hidden=true;};for(const button of panel.querySelectorAll('[data-coil-focus]'))button.onclick=()=>{focus=button.dataset.coilFocus;draw();};
 return {get active(){return !panel.hidden;},open(){panel.hidden=false;focus='all';onRequest();},close(){panel.hidden=true;data=null;svg.replaceChildren();},pending(){data=null;svg.replaceChildren();status.textContent='断面を更新しています…';delete panel.dataset.gap;delete panel.dataset.seam;},error(message){data=null;svg.replaceChildren();status.textContent=message;},update(outputs,q){data=coilSectionData(outputs,q);if(!data.parts.some(p=>p.segments.length)){this.error('断面を表示できませんでした');return;}draw();}};
}
