import * as THREE from 'three';
import {Brush,Evaluator,ADDITION,INTERSECTION} from 'three-bvh-csg';
export function installCombinePreview({scene,host,getMesh,getSelectedIds,computeClearancePreview}){
 const dialog=document.getElementById('tools-dialog'),fields=document.getElementById('cad-fields'),command=document.getElementById('cad-command'),error=document.getElementById('cad-error'),evaluator=new Evaluator();evaluator.useGroups=false;evaluator.attributes=['position','normal'];let preview=null,muted=[],timer=null,revision=0,busy=false,again=false,nextAll=false,ownError=false;
 function clear(){++revision;if(preview){scene.remove(preview);preview.geometry.dispose();preview.material.dispose();preview=null;}for(const [mesh,material] of muted){mesh.material.dispose();mesh.material=material;}muted=[];delete host.dataset.combinePreview;delete host.dataset.combineClearance;}
 function show(geometry,target,tools,mode,matrix){preview=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:0xf04438,transparent:true,opacity:.72,depthTest:false,depthWrite:false,side:THREE.DoubleSide}));if(matrix){preview.matrix.copy(matrix);preview.matrix.decompose(preview.position,preview.quaternion,preview.scale);}preview.renderOrder=50;scene.add(preview);for(const mesh of new Set([target,...tools])){muted.push([mesh,mesh.material]);mesh.material=mesh.material.clone();mesh.material.transparent=true;mesh.material.opacity=.25;mesh.material.depthWrite=false;}host.dataset.combinePreview=mode;}
 async function update(all=false){clear();if(!dialog.open||command.value!=='join'||document.getElementById('cad-apply').disabled)return;if(ownError){error.textContent='';ownError=false;}const mode=document.getElementById('cad-combineMode')?.value;if(!['切り取り','交差'].includes(mode))return;const id=document.getElementById('cad-target')?.value,target=getMesh(id),ids=all?getSelectedIds().filter(x=>x!==id):[document.getElementById('cad-other')?.value];if(!target||!ids.length||ids.includes(id))return;const tools=ids.map(getMesh);if(tools.some(m=>!m))return;const gap=mode==='切り取り'?Number(document.getElementById('cad-cutClearance')?.value||0):0,token=revision;
  if(gap!==0&&computeClearancePreview){
   if(busy){again=true;nextAll=all;return;}busy=true;host.dataset.combinePreview='calculating';ownError=true;error.textContent='すき間を含む切り取り範囲を計算中…';
   try{const result=await computeClearancePreview({type:'join',id:'clearance-preview',target:id,others:ids,combineMode:mode,keepTools:'保持',cutClearance:gap});if(token!==revision||!dialog.open||document.getElementById('cad-apply').disabled)return;const removed=result.removed.find(o=>o.id===id);error.textContent='';ownError=false;if(!removed){host.dataset.combinePreview='empty';return;}const g=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(removed.vertices,3));g.setIndex(removed.triangles);show(g,target,tools,mode);host.dataset.combineClearance=String(gap);
   }catch(e){if(token===revision&&dialog.open&&!document.getElementById('cad-apply').disabled){host.dataset.combinePreview='unavailable';error.textContent=e.message;ownError=true;}}
   finally{busy=false;if(again){again=false;clearTimeout(timer);timer=setTimeout(()=>update(nextAll),60);}}return;
  }
  const geometries=[];try{const brush=mesh=>{const g=mesh.geometry.clone();geometries.push(g);if(!g.attributes.normal)g.computeVertexNormals();const b=new Brush(g);b.applyMatrix4(mesh.matrixWorld);b.updateMatrixWorld(true);return b;};const base=brush(target);let tool=brush(tools[0]);for(const mesh of tools.slice(1)){tool=evaluator.evaluate(tool,brush(mesh),ADDITION);geometries.push(tool.geometry);tool.updateMatrixWorld(true);}const result=evaluator.evaluate(base,tool,INTERSECTION);geometries.push(result.geometry);if(!(result.geometry.index?.count??result.geometry.attributes.position.count)){host.dataset.combinePreview='empty';return;}show(result.geometry.clone(),target,tools,mode,result.matrix);
  }catch{host.dataset.combinePreview='unavailable';}finally{for(const g of new Set(geometries))g.dispose();}
 }
 function schedule(){clear();clearTimeout(timer);timer=setTimeout(()=>update(),120);}
 document.getElementById('tools-form').addEventListener('submit',()=>{clearTimeout(timer);again=false;clear();});
 fields.addEventListener('input',schedule);fields.addEventListener('change',schedule);command.addEventListener('change',schedule);dialog.addEventListener('close',()=>{clearTimeout(timer);again=false;clear();});new MutationObserver(schedule).observe(dialog,{attributes:true,attributeFilter:['open']});new MutationObserver(schedule).observe(fields,{childList:true});
 fields.addEventListener('pointerover',e=>{if(e.target.closest('#join-selected')){clearTimeout(timer);update(true);}});fields.addEventListener('pointerout',e=>{if(e.target.closest('#join-selected'))schedule();});
}
