import {svgSketches} from './svg-sketches.js';
import * as THREE from 'three';
import {roundPointMaterial} from './round-point-material.js';
import {draggablePanel} from './draggable-panel.js';
import {basisFor} from './frames.js';
import {calibrateReference,validateReferenceImage} from './reference-image-data.js';
export async function readReferenceFile(file){
 if(file.size>10000000)throw Error('下絵は10MB以下にしてください');let blob=file;
 if(/\.svg$/i.test(file.name)||file.type==='image/svg+xml'){
  const doc=new DOMParser().parseFromString(await file.text(),'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('SVGを読み込めません');
  if(doc.querySelector('script,foreignObject,iframe,object,embed')||[...doc.querySelectorAll('*')].some(el=>[...el.attributes].some(a=>/^on/i.test(a.name)||(/href$/i.test(a.name)&&a.value&&!a.value.startsWith('#'))))||/@import|url\(\s*['"]?(?!#)/i.test(doc.documentElement.outerHTML))throw Error('外部参照やスクリプトを含まないSVGを使用してください');
  const root=doc.documentElement,view=root.getAttribute('viewBox')?.trim().split(/[ ,]+/).map(Number);if(!root.getAttribute('width'))root.setAttribute('width',String(view?.[2]||1000));if(!root.getAttribute('height'))root.setAttribute('height',String(view?.[3]||1000));blob=new Blob([new XMLSerializer().serializeToString(doc)],{type:'image/svg+xml'});
 }else if(!/^image\/(png|jpeg|webp|gif|bmp)$/.test(file.type))throw Error('PNG・JPEG・WebP・BMP・GIF・SVGを選択してください');
 const url=URL.createObjectURL(blob);
 try{
  const image=new Image();image.src=url;await image.decode();
  if(!image.naturalWidth||!image.naturalHeight)throw Error('画像の大きさを取得できません');
  const scale=Math.min(1,4096/Math.max(image.naturalWidth,image.naturalHeight));
  let width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale));
  const canvas=document.createElement('canvas'),context=canvas.getContext('2d');
  if(!context)throw Error('画像を処理できません');
  const formats=file.type==='image/jpeg'?[['image/jpeg',.88],['image/webp',.88]]:[['image/png'],['image/webp',.88]];
  for(let attempt=0;attempt<8;attempt++){
   canvas.width=width;canvas.height=height;context.imageSmoothingQuality='high';context.drawImage(image,0,0,width,height);
   for(const [format,quality] of formats){
    let data;try{data=canvas.toDataURL(format,quality);}catch{continue;}
    if(data.length<=12000000&&/^data:image\/(png|jpeg|webp);base64,/.test(data))return {data,ratio:image.naturalHeight/image.naturalWidth};
   }
   width=Math.max(1,Math.round(width*.75));height=Math.max(1,Math.round(height*.75));
  }
  throw Error('画像を縮小できませんでした。別の画像を選択してください');
 }finally{URL.revokeObjectURL(url);}
}
export function referenceImages({scene,camera,canvas,host,getFeatures,setFeatures,getPlane,prepare,viewPlane,startSketch,onSvg,notify}){
 const group=new THREE.Group();scene.add(group);const cached=new Map(),marker=new THREE.Group();scene.add(marker);let selected=null,picking=false,points=[],revision=0;
 const panel=document.createElement('div');panel.id='reference-image-panel';panel.hidden=true;panel.innerHTML='<label>下絵<select id="reference-image-list"></select></label><button id="reference-image-add" type="button">写真／SVGを読み込む</button><input id="reference-image-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,.svg" hidden><p id="reference-image-plane"></p><div id="reference-image-fields"><label>名前<input id="reference-image-name" maxlength="100"></label><label>横幅 (mm)<input id="reference-image-width" type="number" min="0.01" max="10000" step="any"></label><div class="row"><label>横位置 (mm)<input id="reference-image-x" type="number" step="any"></label><label>縦位置 (mm)<input id="reference-image-y" type="number" step="any"></label></div><label>回転 (°)<input id="reference-image-angle" type="number" step="any"></label><label>透明度<input id="reference-image-opacity" type="range" min="0.05" max="1" step="0.05"></label><label><input id="reference-image-visible" type="checkbox"> 下絵を表示</label><button id="reference-image-front" type="button">正面から見る</button><button id="reference-image-calibrate" type="button">2点を指定して実寸に合わせる</button><p id="reference-image-hint"></p><div id="reference-image-calibration" hidden><label>2点間の実際の距離 (mm)<input id="reference-image-distance" type="number" min="0.01" max="10000" step="any"></label><button id="reference-image-scale" type="button">寸法を適用</button></div><button id="reference-image-sketch" type="button">この平面でスケッチ</button><button id="reference-image-delete" type="button">下絵を削除</button></div><p id="reference-image-error" role="alert"></p><button id="reference-image-close" type="button">閉じる</button>';host.parentElement.append(panel);draggablePanel(panel,'下絵');const $=id=>panel.querySelector('#reference-image-'+id);
 const button=document.createElement('button');button.id='reference-image-tool';button.innerHTML='<svg class="cad-tool-icon" viewBox="0 0 28 28" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="5" width="22" height="18" rx="1"/><circle cx="10" cy="11" r="2"/><path d="m4 21 7-6 4 3 5-7 5 7"/></svg><span>下絵</span>';button.type='button';document.getElementById('new-circle').after(button);
 function clearPoints(){picking=false;points=[];$('calibration').hidden=true;$('hint').textContent='';for(const child of [...marker.children]){child.geometry.dispose();child.material.map?.dispose();child.material.dispose();marker.remove(child);}}
 function cancel(){++revision;clearPoints();fill();panel.hidden=true;}
 const current=()=>getFeatures().find(f=>f.id===selected&&f.kind==='referenceImage');
 function commit(f){validateReferenceImage(f);setFeatures(getFeatures().map(x=>x.id===f.id?f:x));}
 function fill(){const images=getFeatures().filter(f=>f.kind==='referenceImage');$('list').replaceChildren(...images.map(f=>new Option(f.name,f.id)));if(!images.some(f=>f.id===selected))selected=images[0]?.id||null;$('list').value=selected||'';const f=current();$('fields').hidden=!f;$('plane').textContent=f?'配置平面：'+(f.plane==='CUSTOM'?'選択した面・構築平面':f.plane):'写真は下絵、SVGはスケッチとして、選択中の面・基準平面に取り込みます';if(!f)return;for(const [id,value] of Object.entries({name:f.name,width:Number(f.width.toFixed(2)),x:Number(f.center[0].toFixed(2)),y:Number(f.center[1].toFixed(2)),angle:f.angle,opacity:f.opacity}))$(id).value=value;$('visible').checked=!f.hidden;}
 function refresh(){const ids=new Set();for(const f of getFeatures().filter(f=>f.kind==='referenceImage')){ids.add(f.id);let entry=cached.get(f.id);if(!entry||entry.data!==f.data){if(entry){entry.mesh.geometry.dispose();entry.mesh.material.map?.dispose();entry.mesh.material.dispose();group.remove(entry.mesh);}const texture=new THREE.TextureLoader().load(f.data);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:2,polygonOffsetUnits:2}));mesh.renderOrder=-1;group.add(mesh);entry={mesh,data:f.data};cached.set(f.id,entry);}const b=basisFor(f),m=new THREE.Matrix4().makeBasis(b.u,b.v,b.n),mesh=entry.mesh;mesh.quaternion.setFromRotationMatrix(m);mesh.rotateZ(f.angle*Math.PI/180);mesh.scale.set(f.width,f.height,1);mesh.position.copy(b.u.multiplyScalar(f.center[0]).addScaledVector(b.v,f.center[1]).addScaledVector(b.n,f.offset-.015));mesh.visible=!f.hidden;mesh.material.opacity=f.opacity;mesh.updateMatrixWorld(true);}
 for(const [id,entry] of cached)if(!ids.has(id)){entry.mesh.geometry.dispose();entry.mesh.material.map?.dispose();entry.mesh.material.dispose();group.remove(entry.mesh);cached.delete(id);}if(picking||points.length)clearPoints();fill();host.dataset.referenceImageCount=String(ids.size);}
 function open(id){prepare();if(id)selected=id;clearPoints();fill();panel.hidden=false;panel.scrollTop=0;}
 button.onclick=()=>open();$('list').onchange=()=>{selected=$('list').value;clearPoints();fill();};$('close').onclick=cancel;$('add').onclick=()=>$('file').click();
 $('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;const plane=getPlane(),before=getFeatures(),request=revision;$('add').disabled=true;$('error').textContent='読み込み中…';try{if(/\.svg$/i.test(file.name)||file.type==='image/svg+xml'){if(file.size>5000000)throw Error('SVGは5MB以下にしてください');const text=await file.text();if(request!==revision)return;const sketches=svgSketches(text,plane,file.name);if(getFeatures()!==before)throw Error('モデルが変更されました。もう一度読み込んでください');const number=Math.max(0,...before.filter(f=>f.kind==='sketch').map(f=>f.groupNumber||0))+1;setFeatures([...before,...sketches.map(f=>({...f,groupNumber:number}))]);panel.hidden=true;onSvg?.();$('error').textContent='';notify('SVGをスケッチとして取り込みました。閉じた領域を選んで押し出せます');return;}const {data,ratio}=await readReferenceFile(file);if(request!==revision)return;if(getFeatures()!==before)throw Error('読み込み中にモデルが変わりました。もう一度読み込んでください');const f=validateReferenceImage({id:crypto.randomUUID(),kind:'referenceImage',name:file.name.slice(0,100),...plane,data,width:100,height:100*ratio,center:[0,0],angle:0,opacity:.55,hidden:false});selected=f.id;setFeatures([...before,f]);fill();viewPlane(f);$('error').textContent='';notify('下絵を配置しました。2点を指定して実寸に合わせられます');}catch(e){if(request===revision)$('error').textContent=e.message;}finally{$('add').disabled=false;$('file').value='';}};
 for(const id of ['name','width','x','y','angle','opacity','visible'])$(id).onchange=()=>{const f=current();if(!f)return;try{const width=Number($('width').value);commit({...f,name:$('name').value.trim()||'下絵',width,height:f.height*width/f.width,center:[Number($('x').value),Number($('y').value)],angle:Number($('angle').value),opacity:Number($('opacity').value),hidden:!$('visible').checked});$('error').textContent='';}catch(e){$('error').textContent=e.message;}};
 $('front').onclick=()=>{if(current())viewPlane(current());};$('delete').onclick=()=>{if(current())setFeatures(getFeatures().filter(f=>f.id!==selected));clearPoints();};$('sketch').onclick=()=>{const f=current();if(!f)return;clearPoints();panel.hidden=true;startSketch(f);};
 $('calibrate').onclick=()=>{const f=current();if(!f)return;if(f.hidden){$('error').textContent='下絵を表示してから2点を指定してください';return;}clearPoints();picking=true;viewPlane(f);$('hint').textContent='画像上の1点目をクリック（Escで中止）';$('error').textContent='';};
 const ray=new THREE.Raycaster();canvas.addEventListener('pointerdown',e=>{if(picking&&e.button===0){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});canvas.addEventListener('pointerup',e=>{if(!picking||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();const f=current(),mesh=cached.get(selected)?.mesh;if(!f||!mesh)return;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit){$('hint').textContent='下絵の画像内をクリックしてください';return;}points.push([hit.uv.x,hit.uv.y]);const dot=new THREE.Points(new THREE.BufferGeometry().setFromPoints([hit.point]),roundPointMaterial({color:0xff7000,size:10,depthTest:false}));dot.renderOrder=30;marker.add(dot);if(points.length===2){picking=false;$('calibration').hidden=false;$('hint').textContent='2点を指定しました。実際の距離を入力してください';$('distance').value=Number(Math.hypot((points[1][0]-points[0][0])*f.width,(points[1][1]-points[0][1])*f.height).toFixed(2));$('distance').focus();$('distance').select();}else $('hint').textContent='画像上の2点目をクリック';},{capture:true});
 $('scale').onclick=()=>{try{if(points.length!==2||!current())return;const f=calibrateReference(current(),points[0],points[1],Number($('distance').value));clearPoints();commit(f);$('error').textContent='';notify('下絵を実寸に合わせました');}catch(e){$('error').textContent=e.message;}};
 window.addEventListener('keydown',e=>{if(e.key==='Escape'&&(picking||points.length)){e.preventDefault();e.stopImmediatePropagation();clearPoints();}},{capture:true});
 $('distance').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();$('scale').click();}});
 return {refresh,open,cancel,group,get picking(){return picking;}};
}
