export function createSelectionPicker({host,canvas,canUse,choose,preview,isSelected}){
 const panel=document.createElement('section');panel.id='selection-candidates';panel.hidden=true;panel.setAttribute('aria-label','クリック位置の選択候補');panel.innerHTML='<header><strong>選択候補</strong><button type="button" data-close aria-label="選択候補を閉じる">×</button></header><p>候補に触れると強調表示。クリック／Tabで選択、Shift＋Tabで逆順。</p><div class="selection-candidate-list"></div>';host.append(panel);
 const style=document.createElement('style');style.textContent='#selection-candidates{position:absolute;z-index:110;width:min(270px,calc(100% - 16px));max-height:min(360px,calc(100% - 16px));overflow:auto;padding:10px;background:#f6fbff;color:#234457;border:1px solid #6b99b5;border-radius:9px;box-shadow:0 5px 20px #0003}#selection-candidates[hidden]{display:none}#selection-candidates header{display:flex;align-items:center;justify-content:space-between;height:auto;padding:0;background:none;border:0;color:inherit}#selection-candidates p{font-size:12px;line-height:1.5;margin:8px 0}#selection-candidates button{color:#234457;background:white;border:1px solid #a9c5d8;border-radius:5px;padding:7px;text-align:left}#selection-candidates .selection-candidate-list{display:grid;gap:5px}#selection-candidates button[aria-pressed=true]{background:#d4f1f8;border-color:#047fa6;font-weight:bold}#selection-candidates button:hover,#selection-candidates button:focus-visible{background:#ffe7bd;outline:2px solid #b87922}';document.head.append(style);
 let candidates=[],active=-1,revision;const list=panel.querySelector('.selection-candidate-list');
 function clearPreview(){preview(null);delete host.dataset.selectionCandidatePreview;}
 function close(){panel.hidden=true;candidates=[];active=-1;clearPreview();delete host.dataset.selectionCandidateCount;delete host.dataset.selectionCandidateActive;}
 function highlight(candidate){clearPreview();if(candidate){preview(candidate);host.dataset.selectionCandidatePreview=candidate.key;}}
 function mark(){for(const [i,b]of [...list.children].entries())b.setAttribute('aria-pressed',String(i===active));host.dataset.selectionCandidateActive=candidates[active]?.key||'';}
 function select(index){if(!canUse()||!candidates[index]){close();return;}active=index;clearPreview();choose(candidates[index]);mark();}
 panel.querySelector('[data-close]').onclick=close;panel.addEventListener('pointerleave',clearPreview);
 document.addEventListener('pointerdown',e=>{if(!panel.hidden&&!panel.contains(e.target))close();},{capture:true});
 canvas.addEventListener('wheel',close,{passive:true});window.addEventListener('resize',close);
 window.addEventListener('keydown',e=>{if(panel.hidden)return;if(!canUse()){close();return;}if(e.key==='Tab'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.target.closest('input,textarea,select,[contenteditable]')&&(panel.contains(e.target)||e.target===canvas||e.target===document.body)){e.preventDefault();e.stopImmediatePropagation();select((active+(e.shiftKey?-1:1)+candidates.length)%candidates.length);}},{capture:true});
 return {close,get visible(){return !panel.hidden;},get revision(){return revision;},open(items,event,currentRevision){close();if(items.length<2||!canUse())return;revision=currentRevision;candidates=items;active=items.findIndex(isSelected);list.replaceChildren(...items.map((candidate,i)=>{const b=document.createElement('button');b.type='button';b.dataset.kind=candidate.kind;b.dataset.bodyId=candidate.bodyId;b.dataset.key=candidate.key;b.textContent=candidate.label;b.addEventListener('pointerenter',()=>highlight(candidate));b.addEventListener('focus',()=>highlight(candidate));b.onclick=()=>select(i);return b;}));mark();panel.hidden=false;const rect=host.getBoundingClientRect(),x=event.clientX-rect.left+18,y=event.clientY-rect.top+18;panel.style.left=Math.max(8,Math.min(host.clientWidth-panel.offsetWidth-8,x))+'px';panel.style.top=Math.max(8,Math.min(host.clientHeight-panel.offsetHeight-8,y))+'px';host.dataset.selectionCandidateCount=String(items.length);}};
}
