import {findPanelSpace} from './panel-placement.js';
export function createSelectionPicker({host,canvas,canUse,choose,preview,isSelected,getObstacles=()=>[]}){
 const viewport=host.parentElement;
 const panel=document.createElement('section');panel.id='selection-candidates';panel.hidden=true;panel.setAttribute('aria-label','クリック位置の選択候補');panel.innerHTML='<header><strong>選択候補</strong><button type="button" data-close aria-label="選択候補を閉じる">×</button></header><p>候補に触れると強調表示。クリック／Tabで選択、Shift＋Tabで逆順。</p><div class="selection-candidate-list"></div>';viewport.append(panel);
 const style=document.createElement('style');style.textContent='#selection-candidates{position:absolute;z-index:110;width:min(270px,calc(100% - 16px));max-height:min(360px,calc(100% - 16px));overflow:auto;padding:10px;background:#f6fbff;color:#234457;border:1px solid #6b99b5;border-radius:9px;box-shadow:0 5px 20px #0003}#selection-candidates[hidden]{display:none}#selection-candidates header{display:flex;align-items:center;justify-content:space-between;height:auto;padding:0;background:none;border:0;color:inherit}#selection-candidates p{font-size:12px;line-height:1.5;margin:8px 0}#selection-candidates button{color:#234457;background:white;border:1px solid #a9c5d8;border-radius:5px;padding:7px;text-align:left}#selection-candidates .selection-candidate-list{display:grid;gap:5px}#selection-candidates button[aria-pressed=true]{background:#d4f1f8;border-color:#047fa6;font-weight:bold}#selection-candidates button:hover,#selection-candidates button:focus-visible{background:#ffe7bd;outline:2px solid #b87922}#selection-candidates button{white-space:normal}#selection-candidates small{display:block;font-size:11px;font-weight:normal;line-height:1.5;margin-top:3px;color:#456579} .viewport[data-selection-docked=true] #canvas-host{right:var(--selection-dock-width)} .viewport[data-selection-docked=true]::after{content:"";position:absolute;right:0;top:0;bottom:0;width:var(--selection-dock-width);background:#f4f8fb;border-left:1px solid #c2d3df;z-index:7;pointer-events:none} .viewport[data-selection-docked=true] .view-cube.fusion-view-cube{right:calc(var(--selection-dock-width) + 12px)} .viewport[data-selection-docked=true] #reference-plane-control{right:calc(var(--selection-dock-width) + 16px)} .viewport[data-selection-docked=true] #snap-controls{max-width:calc(100% - var(--selection-dock-width) - 40px);flex-wrap:wrap} .viewport[data-selection-docked=true] .navigation{left:calc((100% - var(--selection-dock-width))/2)} .viewport[data-selection-docked=true] .view-help{right:var(--selection-dock-width)}';document.head.append(style);
 let candidates=[],active=-1,revision;const list=panel.querySelector('.selection-candidate-list');
 function clearPreview(){preview(null);delete host.dataset.selectionCandidatePreview;}
 function releaseDock(){delete viewport.dataset.selectionDocked;viewport.style.removeProperty('--selection-dock-width');}
 function close({keepDock=false}={}){if(!keepDock)releaseDock();panel.hidden=true;candidates=[];active=-1;clearPreview();delete host.dataset.selectionCandidateCount;delete host.dataset.selectionCandidateActive;}
 function highlight(candidate){clearPreview();if(candidate){preview(candidate);host.dataset.selectionCandidatePreview=candidate.key;}}
 function mark(){for(const [i,b]of [...list.children].entries())b.setAttribute('aria-pressed',String(i===active));host.dataset.selectionCandidateActive=candidates[active]?.key||'';}
 function select(index){if(!canUse()||!candidates[index]){close();return;}active=index;clearPreview();choose(candidates[index]);mark();}
 panel.querySelector('[data-close]').onclick=close;panel.addEventListener('pointerleave',clearPreview);
 document.addEventListener('pointerdown',e=>{if(!panel.hidden&&!panel.contains(e.target))close({keepDock:e.target===canvas&&viewport.dataset.selectionDocked==='true'});},{capture:true});
 window.addEventListener('pointerup',()=>{if(panel.hidden)releaseDock();});window.addEventListener('pointercancel',()=>{if(panel.hidden)releaseDock();});
 canvas.addEventListener('wheel',close,{passive:true});window.addEventListener('resize',close);
 window.addEventListener('keydown',e=>{if(panel.hidden)return;if(!canUse()){close();return;}if(e.key==='Tab'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.target.closest('input,textarea,select,[contenteditable]')&&(panel.contains(e.target)||e.target===canvas||e.target===document.body)){e.preventDefault();e.stopImmediatePropagation();select(active<0?(e.shiftKey?candidates.length-1:0):(active+(e.shiftKey?-1:1)+candidates.length)%candidates.length);}},{capture:true});
 return {close,get visible(){return !panel.hidden;},get revision(){return revision;},open(items,event,currentRevision){close();if(items.length<2||!canUse())return;revision=currentRevision;candidates=items;active=items.findIndex(isSelected);list.replaceChildren(...items.map((candidate,i)=>{const b=document.createElement('button');b.type='button';b.dataset.kind=candidate.kind;b.dataset.bodyId=candidate.bodyId;b.dataset.key=candidate.key;b.textContent=candidate.label;if(candidate.detail){const detail=document.createElement('small');detail.textContent=candidate.detail;b.append(detail);}b.addEventListener('pointerenter',()=>highlight(candidate));b.addEventListener('focus',()=>highlight(candidate));b.onclick=()=>select(i);return b;}));mark();panel.hidden=false;panel.style.maxWidth=Math.max(1,viewport.clientWidth-16)+'px';panel.style.maxHeight=Math.max(1,Math.min(360,viewport.clientHeight-16))+'px';const rect=viewport.getBoundingClientRect(),anchor={x:event.clientX-rect.left,y:event.clientY-rect.top},position=findPanelSpace({width:viewport.clientWidth,height:viewport.clientHeight,panelWidth:panel.offsetWidth,panelHeight:panel.offsetHeight,anchor,obstacles:getObstacles()});
 if(position){panel.style.left=position.x+'px';panel.style.top=position.y+'px';panel.dataset.placement='floating';}else{panel.style.maxWidth=Math.max(1,Math.min(270,viewport.clientWidth*.45))+'px';viewport.dataset.selectionDocked='true';viewport.style.setProperty('--selection-dock-width',(panel.offsetWidth+16)+'px');panel.style.left=Math.max(8,viewport.clientWidth-panel.offsetWidth-8)+'px';panel.style.top=Math.max(8,(viewport.clientHeight-panel.offsetHeight)/2)+'px';panel.dataset.placement='docked';}host.dataset.selectionCandidateCount=String(items.length);}};
}
