import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {defaults} from '../src/geometry.js';
const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1550,height:1100},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:5188');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('閉じた'));
const box={...defaults,id:'box',name:'テストボディ',mode:'solid',width:60,height:40,depth:20};const load=async features=>{await page.locator('#file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'forma-cad',version:1,features}))});await page.waitForTimeout(250);};const save=async()=>{const d=page.waitForEvent('download');await page.locator('#save').click();return JSON.parse(await fs.readFile(await(await d).path(),'utf8'));};const face=async()=>{await page.locator('[data-view=top]').click();await page.waitForTimeout(500);const b=await page.locator('canvas').boundingBox();await page.mouse.click(b.x+b.width/2,b.y+b.height/2);assert.match(await page.locator('#measurement-title').textContent(),/ソリッド/);};const command=async(type,fields={})=>{await page.locator('#advanced-tools').click();await page.locator('#cad-command').selectOption(type);for(const [k,v]of Object.entries(fields)){const el=page.locator('#cad-'+k);if(await el.evaluate(n=>n.tagName)==='SELECT')await el.selectOption(String(v));else await el.fill(String(v));}await page.locator('#cad-apply').click();await page.waitForFunction(()=>!document.getElementById('tools-dialog').open||(!document.getElementById('cad-apply').disabled&&!document.getElementById('cad-error').textContent.includes('計算中')),{},{timeout:95000});if(await page.locator('#tools-dialog').isVisible())throw Error(type+': '+await page.locator('#cad-error').textContent());};
await load([box]);await face();await page.keyboard.press('e');assert.equal(await page.locator('#operation').inputValue(),'join');await page.locator('#depth').fill('7');await page.locator('#apply').click();let d=await save();assert.equal(d.features.length,2);assert.equal(d.features[1].region.plane,'CUSTOM');assert.equal(d.features[1].target,'box');console.log('PASS face extrusion');
await page.locator('#cancel').click();await face();await page.locator('#new-line').click();const b=await page.locator('canvas').boundingBox(),step=Number(await page.locator('#canvas-host').getAttribute('data-grid-step'));await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.wheel(0,-1500);await page.waitForTimeout(150);assert.ok(Number(await page.locator('#canvas-host').getAttribute('data-grid-step'))<=step);await page.keyboard.press('Escape');console.log('PASS face sketch and adaptive zoom');
await load([box]);await command('fillet',{radius:2});d=await save();assert.ok(d.features.at(-1).outputs[0].brep);console.log('PASS browser fillet');await command('move',{x:15,angle:20});console.log('PASS browser move');await command('mirror');assert.equal(await page.locator('#body-count').textContent(),'2');console.log('PASS browser mirror');
await load([box]);await command('split',{offset:10});assert.equal(await page.locator('#body-count').textContent(),'2');console.log('PASS browser split');
await load([box]);await command('circular',{count:3});assert.equal(await page.locator('#body-count').textContent(),'3');console.log('PASS circular');
await load([box]);await command('rectangular',{count:2,count2:2});assert.equal(await page.locator('#body-count').textContent(),'4');console.log('PASS rectangular');
await load([box]);await command('coil',{turns:2});console.log('PASS coil');await load([box]);await command('thread',{turns:2});console.log('PASS thread');
await load([{...box,kind:'sketch',id:'s1'},{...box,kind:'sketch',id:'s2',width:30,height:20,z:40}]);await page.locator('#advanced-tools').click();await page.locator('#cad-command').selectOption('loft');await page.locator('input[name=section]').nth(0).check();await page.locator('input[name=section]').nth(1).check();await page.locator('#cad-apply').click();await page.waitForFunction(()=>!document.getElementById('cad-apply').disabled);assert.equal(await page.locator('#cad-error').textContent(),'形状を計算中… 初回はCADエンジンを読み込みます');assert.equal(await page.locator('#tools-dialog').isVisible(),false);console.log('PASS loft');
await load([box]);await face();await command('offset',{offset:5});assert.equal(await page.locator('#plane').inputValue(),'CUSTOM');assert.equal(await page.locator('#z').inputValue(),'25');await page.keyboard.press('Escape');console.log('PASS offset plane');
await command('spline');const c=await page.locator('canvas').boundingBox();for(const [x,y]of [[-.1,0],[0,-.1],[.1,0]])await page.mouse.click(c.x+c.width*(.5+x),c.y+c.height*(.5+y));await page.keyboard.press('Enter');assert.equal(await page.locator('#sketch-count').textContent(),'1');d=await save();assert.equal(d.features.at(-1).profile,'spline');console.log('PASS spline');await page.screenshot({path:'.sites-runtime/advanced-cad.png'});assert.deepEqual(errors,[]);console.log('PASS all browser checks');}finally{await browser.close();}
