import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';
import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {runOperation,kernelBodies} from '../src/kernel.js';import {defaults,validateProject} from '../src/geometry.js';import {solidMeshComplete} from '../src/solid-mesh.js';import {ballJointDefaults,ballJointSettings} from '../src/ball-joint.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const base={...defaults,id:'base',kind:'extrusion',name:'円柱',profile:'circle',diameter:24,depth:40},info=runOperation([base],{type:'ballJointInfo',target:'base'}).analysis,p={...ballJointDefaults(info),id:'ball',type:'ballJoint',target:'base',pose:'assembled'};
console.log('settings',p);console.time('ball joint');const result=runOperation([base],p,progress=>console.log(progress.stage));console.timeEnd('ball joint');assert.equal(result.outputs.length,3);console.log(result.analysis);validateProject({format:'forma-cad',version:1,features:[base,{id:p.id,kind:'cadop',name:'ボールジョイント',spec:p,...result}]});
for(const output of result.outputs){const s=R.deserializeShape(output.brep).asShape3D(),check=new (R.getOC().BRepCheck_Analyzer)(s.wrapped,true,false),solids=s.solids;try{assert.ok(check.IsValid());assert.equal(solids.length,1);assert.ok(solidMeshComplete(s),'all CAD faces have a complete render/export mesh');}finally{check.delete();solids.forEach(q=>q.delete());s.delete();}}
assert.ok(result.analysis.overlap.every(v=>v<1e-5));assert.ok(result.analysis.engagedTurns>=2);assert.ok(result.analysis.availableTravel>result.analysis.clampingTravel+.2);console.log('PASS ball/socket/nut valid with real threads and assembly clearance');

const s=ballJointSettings(info,p),history=[base,{id:p.id,kind:'cadop',name:'ボールジョイント',spec:p,...result}],bodies=kernelBodies(history);try{
 const ball=bodies.get('base'),socket=bodies.get('ball-socket'),nut=bodies.get('ball-nut');
 const slotProbe=R.makeCylinder(.2,2,[s.core-.2,0,s.mouth+1]),slotHit=socket.intersect(slotProbe);try{assert.ok(Math.abs(R.measureVolume(slotHit))<1e-6,'radial slot is open through the collet wall');}finally{slotProbe.delete();slotHit.delete();}
 for(const advance of [s.contactTravel*.4,s.contactTravel+.3]){const turned=nut.clone().rotate(advance/s.threadPitch*360,[0,0,0],[0,0,1]).translate([0,0,advance]),hit=socket.intersect(turned);try{const volume=Math.abs(R.measureVolume(hit));if(advance<s.contactTravel)assert.ok(volume<1e-5,'matching helical threads screw in before the cone contacts');else {assert.ok(volume>.01,'advancing the nut presses the flexible collet');const upper=R.makeBox([-50,-50,s.coneEnd+(advance-s.contactTravel)+.001],[50,50,100]),threadHit=hit.intersect(upper);try{assert.ok(Math.abs(R.measureVolume(threadHit))<1e-5,'pressure is on the tapered seat, not colliding thread teeth');}finally{threadHit.delete();upper.delete();}}}finally{hit.delete();turned.delete();}}
 const tilted=ball.clone().rotate(15,[0,0,p.splitPosition],[0,1,0]);for(const other of [socket,nut]){const hit=tilted.intersect(other);try{assert.ok(Math.abs(R.measureVolume(hit))<1e-5,'ball swivels 15 degrees without stock or neck collision');}finally{hit.delete();}}tilted.delete();
}finally{for(const body of bodies.values())body.delete();}
for(const pose of ['print','exploded']){const next=runOperation([base],{...p,pose});assert.equal(next.outputs.length,3);if(pose==='print')for(const output of next.outputs){const v=output.vertices.filter((_,i)=>i%3===2);assert.ok(Math.abs(Math.min(...v))<1e-5,'all three parts sit on the bed');}console.log('PASS '+pose+' placement');}
for(const plane of ['XZ','YZ']){const source={...base,plane,x:7,y:-3,z:9},next=runOperation([source],p);assert.equal(next.outputs.length,3);assert.ok(Math.abs(next.analysis.axis[plane==='XZ'?1:0])>.999);assert.ok(next.analysis.overlap.every(v=>v<1e-5));console.log('PASS cylinder axis '+plane);}
for(const bad of [{ballDiameter:100},{neckDiameter:14},{splitPosition:2},{threadPitch:4},{threadClearance:.6},{slotCount:3},{wall:0}])assert.throws(()=>runOperation([base],{...p,...bad}));assert.throws(()=>runOperation([{...base,profile:'rect'}],p),/円柱/);assert.throws(()=>runOperation([{...base,mode:'thin'}],p),/円柱/);
console.log('PASS real screw motion/conical pressure, collet slots, swivel clearance, print bed, axes, persistence and invalid geometry');
