import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';
import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {runOperation,kernelBodies} from '../src/kernel.js';import {defaults,validateProject} from '../src/geometry.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const base={...defaults,id:'base',kind:'extrusion',name:'本体',profile:'rect',width:60,height:40,depth:30};
const p={type:'bossJoint',mode:'split',id:'joint',target:'base',plane:'XY',offset:15,pose:'assembled',count:2,diameter:3,length:4,clearance:.25,bossWall:1.6,bossHeight:8,spacing:0,offsetU:0,offsetV:0};
function validResult(result){assert.equal(result.outputs.length,2);for(const o of result.outputs){const s=R.deserializeShape(o.brep).asShape3D(),check=new (R.getOC().BRepCheck_Analyzer)(s.wrapped,true,false),solids=s.solids;try{assert.ok(check.IsValid());assert.equal(solids.length,1);}finally{check.delete();solids.forEach(b=>b.delete());s.delete();}}}
console.time('solid');const joined=runOperation([base],p);console.timeEnd('solid');validResult(joined);assert.equal(joined.analysis.count,2);assert.equal(joined.analysis.holeDiameter,3.5);assert.ok(joined.analysis.overlap<1e-5);console.log('solid',joined.analysis.positions);
const print=runOperation([base],{...p,pose:'print'});validResult(print);for(const o of print.outputs){assert.ok(Math.abs(Math.min(...o.vertices.filter((_,i)=>i%3===2)))<1e-5);}console.log('PASS basic assembled/print boss joint');
const cut=runOperation([base],{type:'split',target:'base',id:'upper',plane:'XY',offset:15}),history=[base,{kind:'cadop',id:'upper',name:'分離',outputs:cut.outputs,remove:cut.remove}],pair=runOperation(history,{...p,mode:'pair',pinTarget:'upper'});validResult(pair);assert.deepEqual(pair.outputs.map(o=>o.id),['base','upper']);
const cavity={...defaults,id:'cavity',name:'空洞',kind:'extrusion',profile:'rect',operation:'cut',target:'base',width:55,height:35,depth:25,z:2.5},hollow=[base,cavity];console.time('hollow');const result=runOperation(hollow,p);console.timeEnd('hollow');validResult(result);assert.ok(result.analysis.positions.every(q=>q.bossHeight>12));const resultHistory=[...hollow,{kind:'cadop',id:p.id,name:'ボス接合',spec:p,...result}],bodies=kernelBodies(resultHistory);try{const probe=R.makeCylinder(1,3,[result.analysis.positions[0].point[0],result.analysis.positions[0].point[1],11]);const hole=bodies.get('base').intersect(probe);try{assert.ok(R.measureVolume(hole)<1e-7,'receiver hole is empty');}finally{hole.delete();probe.delete();}}finally{for(const b of bodies.values())b.delete();}validateProject({format:'forma-cad',version:1,features:resultHistory});console.log('PASS hollow boss reaches floor and rod reaches roof, independent solids and save validation');
for(const plane of ['XZ','YZ']){const result=runOperation([base],{...p,plane,offset:plane==='XZ'?0:0});validResult(result);console.log('PASS '+plane);}
import {makeBossJoint} from '../src/boss-joint.js';
for(const count of [1,4]){const result=runOperation([base],{...p,count});validResult(result);assert.equal(result.analysis.positions.length,count);assert.ok(result.analysis.overlap<1e-5);}
const round=runOperation([{...base,profile:'circle',diameter:50}],{...p,count:4});validResult(round);assert.equal(round.analysis.count,4);
const assembled=kernelBodies([base,{kind:'cadop',id:p.id,name:'ボス接合',spec:p,...joined}]);try{
 const receiver=assembled.get('base'),male=assembled.get('joint-pin'),q=joined.analysis.positions[0],pt=q.point;
 for(const [name,radius,z,height,wantMaterial]of [['clearance',1.7,12,2,false],['blind bottom',1.7,10,0.5,true]]){
  const probe=R.makeCylinder(radius,height,[pt[0],pt[1],z]);const hit=receiver.intersect(probe);try{assert.equal(R.measureVolume(hit)>1e-6,wantMaterial,name);}finally{hit.delete();probe.delete();}
 }
 const probe=R.makeCylinder(1,2,[pt[0],pt[1],12]),hit=male.intersect(probe);try{assert.ok(Math.abs(R.measureVolume(hit)-Math.PI*2)<1e-6,'rod is present at designed insertion position');}finally{hit.delete();probe.delete();}
}finally{for(const shape of assembled.values())shape.delete();}
const pairBodies=kernelBodies(history);try{
 const a=pairBodies.get('base').rotate(28,[0,0,0],[1,1,0]).translate([7,-3,9]),b=pairBodies.get('upper').rotate(28,[0,0,0],[1,1,0]).translate([7,-3,9]);const sourceVolume=R.measureVolume(a);try{
  const result=makeBossJoint(a,b,{...p,mode:'pair',pinTarget:'upper',pose:'print'});try{assert.equal(result.parts.length,2);assert.equal(result.analysis.count,2);for(const shape of result.parts){const box=shape.boundingBox;try{assert.ok(Math.abs(box.bounds[0][2])<1e-5);}finally{box.delete();}}assert.equal(R.measureVolume(a),sourceVolume,'source remains unchanged');}finally{result.parts.forEach(shape=>shape.delete());}
  const swapped=makeBossJoint(b,a,{...p,mode:'pair',target:'upper',pinTarget:'base'});swapped.parts.forEach(shape=>shape.delete());
  const far=b.clone().translate([0,0,100]);try{assert.throws(()=>makeBossJoint(a,far,{...p,mode:'pair',pinTarget:'upper'}),/接している/);}finally{far.delete();}
 }finally{a.delete();b.delete();}
}finally{for(const shape of pairBodies.values())shape.delete();}
for(const [change,message]of [[{offset:0},/内部/],[{clearance:0},/すき間/],[{bossHeight:2},/ボス高さ/],[{count:3},/接合の数/],[{offsetU:100},/広さ/],[{diameter:50},/広さ/]])assert.throws(()=>runOperation([base],{...p,...change}),message);
console.log('PASS 1/2/4 joints, circular outline, blind hole/clearance/pin dimensions, rotated/swapped pair, source immutability and invalid inputs');
for(const reinforcement of ['round','ribs']){
 const reinforced=runOperation(hollow,{...p,reinforcement,reinforcementSize:1.2});validResult(reinforced);assert.equal(reinforced.analysis.reinforcement.applied,2);assert.ok(reinforced.analysis.positions.every(q=>q.reinforcement.boss===1.2&&q.reinforcement.pin===1.2));assert.ok(reinforced.analysis.overlap<1e-5);const unreinforcedVolumes=result.outputs.map(o=>{const s=R.deserializeShape(o.brep).asShape3D();try{return R.measureVolume(s);}finally{s.delete();}});reinforced.outputs.forEach((o,i)=>{const s=R.deserializeShape(o.brep).asShape3D();try{assert.ok(R.measureVolume(s)>unreinforcedVolumes[i]+1);}finally{s.delete();}});console.log('PASS '+reinforcement+' reinforces both hollow roots without interference');
}
const manual=runOperation(hollow,{...p,jointPositions:[[-10,3],[12,4]]});validResult(manual);assert.deepEqual(manual.analysis.positions.map(q=>q.uv),[[-10,3],[12,4]]);
const closeWall=runOperation(hollow,{...p,count:1,jointPositions:[[23.5,0]]});assert.ok(closeWall.analysis.warnings.length>0,'warn when near an inner wall');assert.throws(()=>runOperation(hollow,{...p,count:1,jointPositions:[[40,0]]}),/広さ/);assert.throws(()=>runOperation(hollow,{...p,jointPositions:[[0,0],[0,0]]}),/広さ/);assert.throws(()=>runOperation(hollow,{...p,jointPositions:[[1,2]]}),/座標/);
for(const plane of ['XZ','YZ'])for(const reinforcement of ['round','ribs']){const check=runOperation(hollow,{...p,plane,offset:0,reinforcement,reinforcementSize:1});validResult(check);assert.ok(check.analysis.positions.every(q=>q.reinforcement.boss===1&&q.reinforcement.pin===1));}
const shortPin=runOperation([base,{...cavity,depth:13.3}],{...p,reinforcement:'round',reinforcementSize:1.2});validResult(shortPin);assert.ok(shortPin.analysis.positions.every(q=>q.reinforcement.pin>=.2&&q.reinforcement.pin<.6));assert.ok(shortPin.analysis.overlap<1e-5);
const buried=runOperation([base],{...p,reinforcement:'ribs',reinforcementSize:10});validResult(buried);assert.equal(buried.analysis.reinforcement.applied,0);assert.deepEqual(buried.analysis.positions.map(q=>q.uv),joined.analysis.positions.map(q=>q.uv));
for(const change of [{reinforcement:'unknown'},{reinforcement:'round',reinforcementSize:0},{symmetricPlacement:'yes'},{jointPositions:[[NaN,0],[1,2]]}])assert.throws(()=>runOperation(hollow,{...p,...change}));
console.log('PASS reinforced XZ/YZ, limited space at root, unchanged solid fit and reinforcement validation');
const shellSpec={...p,shellEnabled:true,shellThickness:2},shelled=runOperation([base],shellSpec);validResult(shelled);assert.deepEqual(shelled.analysis.shell.parts.map(q=>q.status),['created','created']);assert.ok(shelled.analysis.shell.parts.every(q=>q.removedVolume>20000));assert.ok(shelled.analysis.positions.every(q=>Math.abs(q.bossBase-2)<1e-4&&Math.abs(q.pinBase-28)<1e-4));assert.ok(shelled.analysis.overlap<1e-5);
const shellBodies=kernelBodies([base,{kind:'cadop',id:'joint',name:'中空ボス接合',spec:shellSpec,...shelled}]);try{
 for(const [id,z,height]of [['base',3,10],['joint-pin',16,10]]){const probe=R.makeCylinder(2,height,[0,0,z]),hit=shellBodies.get(id).intersect(probe);try{assert.ok(R.measureVolume(hit)<1e-6,'both interiors are hollow');}finally{hit.delete();probe.delete();}}
 for(const [id,z]of [['base',.2],['joint-pin',28.2]]){const probe=R.makeCylinder(1,1,[0,0,z]),hit=shellBodies.get(id).intersect(probe);try{assert.ok(Math.abs(R.measureVolume(hit)-Math.PI)<1e-6,'bottom and roof remain solid');}finally{hit.delete();probe.delete();}}
 for(const [id,z]of [['base',4],['joint-pin',19]]){const probe=R.makeBox([28.2,-1,z],[29.2,1,z+1]),hit=shellBodies.get(id).intersect(probe);try{assert.ok(Math.abs(R.measureVolume(hit)-2)<1e-5,'outer side wall is retained');}finally{hit.delete();probe.delete();}}
}finally{for(const shape of shellBodies.values())shape.delete();}
for(const reinforcement of ['round','ribs']){const check=runOperation([base],{...shellSpec,reinforcement,reinforcementSize:1.2});validResult(check);assert.equal(check.analysis.reinforcement.applied,2);}
for(const plane of ['XZ','YZ']){const check=runOperation([base],{...shellSpec,plane,offset:0});validResult(check);assert.ok(check.analysis.shell.parts.every(q=>q.status==='created'));}
const roundShell=runOperation([{...base,profile:'circle',diameter:50}],shellSpec);validResult(roundShell);assert.equal(roundShell.analysis.shell.parts[0].status,'created');
const pairShell=runOperation(history,{...shellSpec,mode:'pair',pinTarget:'upper'});validResult(pairShell);assert.deepEqual(pairShell.outputs.map(o=>o.id),['base','upper']);
const existing=runOperation(hollow,{...shellSpec,shellThickness:4});validResult(existing);assert.ok(existing.analysis.shell.parts.every(q=>q.status==='existing'));existing.outputs.forEach((o,i)=>{const a=R.deserializeShape(o.brep).asShape3D(),b=R.deserializeShape(result.outputs[i].brep).asShape3D(),difference=a.cut(b),reverse=b.cut(a);try{assert.ok(R.measureVolume(difference)<1e-6&&R.measureVolume(reverse)<1e-6,'existing open cavities retain their wall thickness');}finally{a.delete();b.delete();difference.delete();reverse.delete();}});
const thick=runOperation([base],{...shellSpec,shellThickness:3});validResult(thick);assert.ok(thick.analysis.positions.every(q=>Math.abs(q.bossBase-3)<1e-4&&Math.abs(q.pinBase-27)<1e-4));
for(const change of [{shellEnabled:'yes'},{shellThickness:0},{shellThickness:NaN},{shellThickness:15},{shellThickness:50}])assert.throws(()=>runOperation([base],{...shellSpec,...change}),/中空|シェル|壁厚/);
const shellPairBodies=kernelBodies(history);try{
 const a=shellPairBodies.get('base').clone().rotate(28,[0,0,0],[1,1,0]).translate([7,-3,9]),b=shellPairBodies.get('upper').clone().rotate(28,[0,0,0],[1,1,0]).translate([7,-3,9]),volumes=[R.measureVolume(a),R.measureVolume(b)];try{
  const joint=makeBossJoint(a,b,{...shellSpec,mode:'pair',pinTarget:'upper',pose:'print'});try{assert.ok(joint.analysis.shell.parts.every(q=>q.status==='created'));assert.deepEqual([R.measureVolume(a),R.measureVolume(b)],volumes,'hollowing preserves source bodies');for(const shape of joint.parts){const box=shape.boundingBox;try{assert.ok(Math.abs(box.bounds[0][2])<1e-5,'hollow print parts sit on the bed');}finally{box.delete();}}}finally{joint.parts.forEach(shape=>shape.delete());}
 }finally{a.delete();b.delete();}
}finally{for(const shape of shellPairBodies.values())shape.delete();}
console.log('PASS shell before joints: split/pair, both cavities, walls/floors, thickness edits, circular/XZ/YZ, reinforcement, existing hollow preservation and invalid inputs');
