import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';
import * as R from 'replicad';
import {makeCoilJoint,resolveCoilJoint} from '../src/coil-joint.js';
import {filletCoilExteriors} from '../src/coil-fillet.js';
import {validateCoilPreset} from '../src/coil-presets.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const params={wire:2,pitch:4,turns:2,wall:2.9,jointGap:.4,jointSeam:0,jointSplit:30,hand:'右ねじ',autoAdjust:true,alignStop:false,closeAngle:0,jointPose:'閉じた状態',rimSeat:true,jointLatch:true,latchGap:.2,latchEngagement:.9,latchFirm:true};
assert.equal(validateCoilPreset(params).autoFillet,false);assert.equal(validateCoilPreset(params).filletRadius,2);assert.equal(validateCoilPreset({...params,autoFillet:true,filletRadius:.8}).filletRadius,.8);const migrated=validateCoilPreset({...params,autoFillet:true,filletRadius:.8});assert.equal(migrated.filletVerticalRadius,.8);assert.equal(migrated.filletCapRadius,.8);const separate=validateCoilPreset({...params,autoFillet:true,filletVerticalRadius:8,filletCapRadius:.8});assert.equal(separate.filletVerticalRadius,8);assert.equal(separate.filletCapRadius,.8);assert.throws(()=>validateCoilPreset({...params,autoFillet:'yes'}));assert.throws(()=>validateCoilPreset({...params,autoFillet:true,filletRadius:0}));
const data=JSON.parse(await fs.readFile('../修正版/design.forma(26)-内蔵爪・回転止め強化.forma.json','utf8')),f=data.features.find(f=>f.spec?.type==='coilJoint'),q={...f.analysis,autoFillet:true,filletRadius:.5,requestedFilletRadius:.5};
const body=R.deserializeShape(f.outputs[0].brep),raw=R.deserializeShape(f.outputs[1].brep),flipped=raw.clone().rotate(180,[0,0,0],[1,0,0]),bb=flipped.boundingBox,b=bb.bounds;bb.delete();const lid=flipped.translate([-(b[0][0]+b[1][0])/2,-(b[0][1]+b[1][1])/2,q.split-b[0][2]]);raw.delete();flipped.delete();
function volume(shape){return Math.abs(R.measureVolume(shape));}
function watertight(shape){const m=shape.mesh({tolerance:.05,angularTolerance:.15}),keys=Array.from({length:m.vertices.length/3},(_,i)=>m.vertices.slice(i*3,i*3+3).map(v=>Math.round(v*1e7)).join(',')),edges=new Map();for(let i=0;i<m.triangles.length;i+=3){if(new Set(m.triangles.slice(i,i+3).map(index=>keys[index])).size<3)continue;for(let j=0;j<3;j++){const a=keys[m.triangles[i+j]],b=keys[m.triangles[i+(j+1)%3]];if(a===b)continue;const k=[a,b].sort().join('|');edges.set(k,(edges.get(k)||0)+1);}}console.log('mesh edges',m.triangles.length/3,[...edges.values()].filter(count=>count===1).length,[...edges.values()].filter(count=>count>2).length);assert.ok([...edges.values()].every(count=>count===2),'watertight manifold mesh');}
for(const [key,lidOnly] of [['filletBodyBottom',false],['filletLidTop',true]]){const selective=filletCoilExteriors(body,lid,{...q,filletBodyBottom:!lidOnly,filletLidTop:lidOnly,filletVertical:false});try{assert.equal(selective.analysis.verticalCorners,false);assert.equal(selective.analysis.locations.bodyBottom,!lidOnly);assert.equal(selective.analysis.locations.lidTop,lidOnly);assert.equal(selective.analysis.edges[lidOnly?0:1],0);assert.ok(Math.abs(volume(selective.parts[lidOnly?0:1])-volume(lidOnly?body:lid))<1e-7);assert.ok(volume(selective.parts[lidOnly?1:0])<volume(lidOnly?lid:body));selective.parts.forEach(watertight);}finally{selective.parts.forEach(s=>s.delete());}}
const rounded=filletCoilExteriors(body,lid,q);try{assert.equal(rounded.analysis.verticalCorners,true);assert.equal(rounded.analysis.radius,.5);for(const [i,s] of rounded.parts.entries()){watertight(s);assert.ok(volume(s)<volume([body,lid][i]));const source=[body,lid][i],tool=R.makeCylinder(q.radius+.5,q.neckLength+.5,[0,0,q.split-.001]),difference=source.cut(s),hit=difference.intersect(tool);try{assert.ok(volume(hit)<1e-5,'fillet removes no internal engagement geometry');}finally{tool.delete();difference.delete();hit.delete();}}
console.log('PASS printed hex fillet, outside only, unchanged engagement, water tight');
}finally{rounded.parts.forEach(s=>s.delete());body.delete();lid.delete();}
const info={...q,profile:undefined,shapeType:'cylinder',radius:17.32,height:50};assert.equal(resolveCoilJoint(info,params).autoFillet,false);assert.throws(()=>resolveCoilJoint(info,{...params,autoFillet:true,filletRadius:-1}));assert.throws(()=>resolveCoilJoint(info,{...params,autoFillet:'yes'}));assert.throws(()=>resolveCoilJoint(info,{...params,autoFillet:true,filletBodyBottom:false,filletLidTop:false,filletVertical:true}),/円柱/);assert.throws(()=>resolveCoilJoint(info,{...params,autoFillet:true,filletBodyBottom:false,filletLidTop:false,filletVertical:false}),/1つ以上/);assert.equal(validateCoilPreset(params).filletBodyBottom,true);assert.equal(validateCoilPreset(params).filletLidTop,true);assert.equal(validateCoilPreset(params).filletVertical,true);
const limited=resolveCoilJoint(info,{...params,autoFillet:true,filletRadius:10});assert.ok(limited.filletRadius<10);
const base=R.makeBox([-25,-25,0],[25,25,80]),p={...params,jointSplit:60,autoFillet:true,filletRadius:.5};let last='';const stages=[],cachedPreview=makeCoilJoint(base,{...p,filletRadius:.4},progress=>stages.push(progress.stage),{preview:true});cachedPreview.parts.forEach(s=>s.delete());assert.ok(stages.some(stage=>/コイル/.test(stage)));stages.length=0;const changed=makeCoilJoint(base,p,progress=>stages.push(progress.stage),{preview:true});changed.parts.forEach(s=>s.delete());assert.ok(stages.includes('コイルと爪の形状を再利用しています'));assert.ok(!stages.some(stage=>/本体を|受け溝/.test(stage)));stages.length=0;const selectivePreview=makeCoilJoint(base,{...p,filletBodyBottom:true,filletLidTop:false,filletVertical:false},progress=>stages.push(progress.stage),{preview:true});try{assert.ok(stages.includes('コイルと爪の形状を再利用しています'));assert.deepEqual(selectivePreview.analysis.fillet.locations,{bodyBottom:true,lidTop:false,vertical:false});}finally{selectivePreview.parts.forEach(s=>s.delete());}
const result=makeCoilJoint(base,p,progress=>{if(progress.stage!==last){console.log(progress.stage);last=progress.stage;}});
try{assert.equal(result.analysis.motion.status,'clear');assert.equal(result.analysis.motion.checks.length,29);assert.equal(result.analysis.fillet.status,'clear');assert.equal(result.analysis.fillet.radius,.5);assert.equal(result.analysis.fillet.verticalCorners,true);result.parts.forEach(watertight);console.log('PASS full square automatic fillet + all29 opening checks + native watertight solids');}finally{result.parts.forEach(s=>s.delete());}
stages.length=0;const again=makeCoilJoint(base,p,progress=>stages.push(progress.stage),{preview:true});assert.equal(again.analysis.motion.status,'clear');assert.ok(!stages.some(stage=>/干渉/.test(stage)));again.parts.forEach(s=>s.delete());stages.length=0;const changedCore=makeCoilJoint(base,{...p,pitch:4.2},progress=>stages.push(progress.stage),{preview:true});changedCore.parts.forEach(s=>s.delete());assert.ok(!stages.includes('コイルと爪の形状を再利用しています'));base.delete();console.log('PASS core reuse, variant reuse, locations, core change invalidation');
