import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import * as THREE from 'three';import {runOperation} from '../src/kernel.js';import {defaults,rebuild} from '../src/geometry.js';import {planarFace} from '../src/frames.js';import {sectionSegments,sectionCap} from '../src/section-view.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const body=R.makeBox([-20,-20,0],[20,20,40]).cut(R.makeCylinder(8,40)).fuse(R.makeCylinder(8,2,[0,0,34]).cut(R.makeCylinder(6,2,[0,0,34])));
const base={kind:'cadop',id:'b',name:'hole with internal ridge',outputs:[{id:'b',...body.mesh(),planarFaces:body.faces.filter(f=>f.geomType==='PLANE').map(f=>f.hashCode),brep:body.serialize()}],remove:[]};const g=rebuild([base]).get('b').geometry,p=g.attributes.position,ix=g.index;let t=-1;for(let i=0;i<(ix?ix.count:p.count);i+=3)if([0,1,2].every(j=>Math.abs(p.getZ(ix?ix.getX(i+j):i+j)-40)<1e-5)){t=i/3;break;}
const region={...planarFace(g,t),bodyId:'b',cadFace:{bodyId:'b',point:[15,0,40],normal:[0,0,1]}},f={...defaults,kind:'extrusion',id:'c',profile:'region',plane:'CUSTOM',frame:region.frame,region,depth:-10,z:40,operation:'cut',target:'b'};
for(const capHoles of [false,true]){const result=runOperation([base],{type:'extrusionBatch',features:[{...f,capHoles}]}).features[0];const shape=R.deserializeShape(result.cadResult.outputs[0].brep).asShape3D();const probe=R.makeCylinder(7,1,[0,0,34.5]).cut(R.makeCylinder(6.5,1,[0,0,34.5]));const overlap=shape.intersect(probe);assert.ok(capHoles?R.measureVolume(overlap)<1e-6:R.measureVolume(overlap)>1);}
for(const [z,depth] of [[40,-1],[0,1]]){const cut={...defaults,kind:'extrusion',id:'c',profile:'circle',diameter:8,x:13,z,depth,operation:'cut',target:'b',throughAll:true};const result=runOperation([base],{type:'extrusionBatch',features:[cut]}).features[0];const shape=R.deserializeShape(result.cadResult.outputs[0].brep).asShape3D();assert.ok(Math.abs(R.measureVolume(body)-R.measureVolume(shape)-Math.PI*16*40)<.001);}
const section=new THREE.Plane(new THREE.Vector3(0,0,1),-20),segments=sectionSegments(g,section),cap=sectionCap(segments,section);assert.ok(segments.length>0);const pos=cap.attributes.position;let area=0;for(let i=0;i<pos.count;i+=3){const a=new THREE.Vector3().fromBufferAttribute(pos,i),b=new THREE.Vector3().fromBufferAttribute(pos,i+1),c=new THREE.Vector3().fromBufferAttribute(pos,i+2);area+=b.sub(a).cross(c.sub(a)).length()/2;}assert.ok(Math.abs(area-(1600-Math.PI*64))<2,'section cap keeps hole open');await fs.writeFile('.sites-runtime/cut-options-fixture.json',JSON.stringify({format:'forma-cad',version:1,features:[base]}));console.log('PASS capped cut removes interior ridge, through both directions, section cap preserves hole');

for(const operation of ['new','join']){const feature={...f,depth:5,capHoles:true,operation};const result=runOperation([base],{type:'extrusionBatch',features:[feature]}).features[0];const shape=R.deserializeShape(result.cadResult.outputs[0].brep).asShape3D();assert.ok(Math.abs(R.measureVolume(shape)-(operation==='new'?8000:R.measureVolume(body)+8000))<.001);assert.equal(result.cadResult.outputs[0].id,operation==='new'?'c':'b');const probe=R.makeCylinder(2,3,[0,0,41]);assert.ok(R.measureVolume(shape.intersect(probe))>37);const before=[base,result],next=structuredClone(before);next[1].depth=8;delete next[1].cadResult;const edited=runOperation(next,{type:'replay',before,start:1}).features[1];const editShape=R.deserializeShape(edited.cadResult.outputs[0].brep).asShape3D();assert.ok(Math.abs(R.measureVolume(editShape)-(operation==='new'?12800:R.measureVolume(body)+12800))<.001);}
console.log('PASS closed lid as new solid and join, center filled, depth replay');
