import * as R from 'replicad';import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {encloseBody,encloseParts} from '../src/enclose.js';import {runOperation} from '../src/kernel.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const valid=s=>{const c=new (R.getOC().BRepCheck_Analyzer)(s.wrapped,true,false);try{assert.ok(c.IsValid());}finally{c.delete();}};
const volume=s=>R.measureVolume(s),empty=(s,probe,label)=>{const c=s.intersect(probe);try{assert.ok(Math.abs(volume(c))<1e-5,label);}finally{c.delete();probe.delete();}};
const b=R.makeBox([0,0,0],[10,20,30]),original=b.serialize(),top={bodyId:'base',point:[5,10,30],normal:[0,0,1]},bottom={bodyId:'base',point:[5,10,0],normal:[0,0,-1]};
const t=2,g=.5,outer=d=>2200*d+Math.PI*60*d*d+4*Math.PI*d**3/3;
let closed=encloseBody(b,t,{clearance:g});assert.equal(b.serialize(),original);valid(closed);assert.ok(Math.abs(volume(closed)-(outer(g+t)-outer(g)))<.001);empty(closed,R.makeBox([-.49,1,1],[10.49,19,29]),'clearance on both sides');
for(const faces of [[top],[top,bottom]]){const s=encloseBody(b,t,{clearance:g,faces});valid(s);assert.equal(b.serialize(),original);empty(s,R.makeBox([1,1,29],[9,19,34]),'open top');empty(s,R.makeBox([-.49,1,1],[10.49,19,29]),'open shell clearance');if(faces.length===2)empty(s,R.makeBox([1,1,-4],[9,19,1]),'open bottom');const bounds=s.boundingBox.bounds;assert.ok(Math.abs(bounds[1][2]-30)<1e-5);s.delete();}
for(const [enclosureSplit,splitOffset] of [['XY',15],['XZ',10],['YZ',5]]){const parts=encloseParts(b,{thickness:t,clearance:g,enclosureSplit,splitOffset});assert.equal(parts.length,2);parts.forEach(valid);assert.ok(Math.abs(parts.reduce((n,s)=>n+volume(s),0)-volume(closed))<1e-4);empty(parts[0],parts[1].clone(),'split parts do not overlap');parts.forEach(s=>s.delete());}
assert.throws(()=>encloseParts(b,{thickness:t,enclosureSplit:'XY',splitOffset:100}),/横切/);for(const clearance of [-1,NaN,Infinity,1001])assert.throws(()=>encloseBody(b,t,{clearance}),/すき間/);
const features=[{kind:'cadop',id:'source',outputs:[{id:'base',brep:original}],remove:[]}],spec={type:'enclose',id:'enclosure',target:'base',thickness:t,clearance:g,faces:[top],enclosureSplit:'YZ',splitOffset:5};const result=runOperation(features,spec);assert.deepEqual(result.remove,[]);assert.deepEqual(result.outputs.map(o=>o.id),['enclosure','enclosure-part2']);for(const o of result.outputs){const s=R.deserializeShape(o.brep).asShape3D();valid(s);s.delete();}assert.equal(b.serialize(),original);
const cylinder=R.makeCylinder(10,20);const c=encloseBody(cylinder,1,{clearance:.3,faces:[{point:[0,0,20],normal:[0,0,1]}]});valid(c);empty(c,R.makeCylinder(9,5).translate([0,0,18]),'cylinder opening');c.delete();cylinder.delete();closed.delete();b.delete();console.log('PASS clearance exact volume, open top/multiple faces/cylinder, split XYZ volumes and nonoverlap, unchanged source, invalid settings, new body IDs and BREP roundtrip');
