import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {runOperation,kernelBodies} from '../src/kernel.js';import {defaults,rebuild} from '../src/geometry.js';import {planarFace} from '../src/frames.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const frame={...defaults,id:'frame',kind:'extrusion',name:'frame',profile:'rect',mode:'thin',width:60,height:40,wall:2,side:'inside',depth:30,operation:'new'};
for(const original of [frame,{...frame,mode:'solid',profile:'region',region:{plane:'XY',offset:0,outer:[[-30,-20],[30,-20],[30,20],[-30,20]],holes:[[[-28,-18],[-28,18],[28,18],[28,-18]]],sourceIds:[]}}]){
 const bodies=kernelBodies([original]),base=bodies.get('frame');assert.ok(Math.abs(R.measureVolume(base)-(60*40-56*36)*30)<.001,'frame must stay hollow in kernel');
 const geometry=rebuild([original]).get('frame').geometry,p=geometry.attributes.position,ix=geometry.index;let t=-1;for(let i=0;i<(ix?ix.count:p.count);i+=3)if([0,1,2].every(j=>Math.abs(p.getZ(ix?ix.getX(i+j):i+j)-30)<1e-5)){t=i/3;break;}
 const region={...planarFace(geometry,t),bodyId:'frame'},lid={...defaults,id:'lid',name:'lid',kind:'extrusion',mode:'solid',profile:'region',plane:region.plane,frame:region.frame,region,z:30,depth:3,capHoles:true,operation:'join',target:'frame'};
 const result=runOperation([original],{type:'extrusionBatch',features:[lid]}).features[0],shape=R.deserializeShape(result.cadResult.outputs[0].brep).asShape3D();assert.ok(Math.abs(R.measureVolume(shape)-((60*40-56*36)*30+60*40*3))<.001);for(const z of [0,1,15,28]){const probe=R.makeBox([-5,-5,z],[5,5,z+1]);assert.ok(Math.abs(R.measureVolume(shape.intersect(probe)))<1e-7,'bottom and interior stay open');}assert.ok(R.measureVolume(shape.intersect(R.makeBox([-5,-5,31],[5,5,32])))>99);}
await fs.writeFile('.sites-runtime/frame-lid-fixture.json',JSON.stringify({format:'forma-cad',version:1,features:[frame]}));console.log('PASS thin frame and region frame retain open bottom/interior after joined lid');
