import assert from 'node:assert/strict';import {KernelClient,kernelTimeout} from '../src/kernel-client.js';
for(const type of ['coilJoint']){assert.equal(kernelTimeout([],{type}),600000);assert.equal(kernelTimeout([],{type:'preview',operation:{type}}),600000);}assert.equal(kernelTimeout([{kind:'cadop',spec:{type:'coilJoint'}}],{type:'replay',start:0}),600000);assert.equal(kernelTimeout([{spec:{type:'coilJoint'}},{spec:{type:'move'}}],{type:'replay',start:1}),90000);assert.equal(kernelTimeout([],{type:'preview',operation:{type:'pull'}}),300000);assert.equal(kernelTimeout([],{type:'move'}),90000);
assert.equal(kernelTimeout([],{type:'svgWrap'}),300000);assert.equal(kernelTimeout([],{type:'preview',operation:{type:'svgWrap'}}),300000);assert.equal(kernelTimeout([{spec:{type:'svgWrap'}}],{type:'replay',start:0}),300000);assert.equal(kernelTimeout([{spec:{type:'svgWrap'}},{spec:{type:'move'}}],{type:'replay',start:1}),90000);
let worker;const client=new KernelClient(()=>worker={messages:[],postMessage(m){this.messages.push(m);},terminate(){this.dead=true;}}),progress=[];
const active=client.request({spec:{type:'coilJoint'}},1000,p=>progress.push(p)),queued=client.request({spec:{type:'move'}},5);assert.equal(worker.messages.length,1);assert.equal(client.pending.get(2).timer,null);await new Promise(r=>setTimeout(r,20));assert.ok(!worker.dead);assert.equal(client.pending.size,2);worker.onmessage({data:{id:1,progress:{stage:'検査',current:1,total:7}}});assert.equal(client.pending.size,2);assert.equal(progress[0].stage,'検査');worker.onmessage({data:{id:1,result:{ok:true}}});assert.equal(worker.messages.length,2);worker.onmessage({data:{id:2,result:{ok:true}}});await Promise.all([active,queued]);assert.equal(client.pending.size,0);
const failing=client.request({},1000),next=client.request({},1000),failure=assert.rejects(failing,/invalid/);worker.onmessage({data:{id:3,error:'invalid'}});worker.onmessage({data:{id:4,result:{ok:true}}});await failure;await next;
const cancelled=client.request({},1000),waiting=client.request({},5),cancelA=assert.rejects(cancelled,/キャンセル/),cancelB=assert.rejects(waiting,/キャンセル/);client.reset();await Promise.all([cancelA,cancelB]);assert.ok(worker.dead);assert.equal(client.pending.size,0);console.log('PASS coil preview/apply/replay deadlines, queued short job does not cancel active long job, progress messages, error continuation and cancellation');

let attempts=0,recovered;const factoryClient=new KernelClient(()=>{if(!attempts++)throw Error('factory failed');return recovered={postMessage(m){this.message=m;},terminate(){}};});await assert.rejects(factoryClient.request({}),/factory failed/);assert.equal(factoryClient.pending.size,0);const retry=factoryClient.request({});assert.equal(recovered.message.id,2);recovered.onmessage({data:{id:2,result:'ready'}});assert.equal(await retry,'ready');
const preview=client.request({spec:{type:'preview'}},1000),cancelPreview=assert.rejects(preview,/キャンセル/);client.cancelPreviews();await cancelPreview;assert.ok(worker.dead);
const ordinary=client.request({spec:{type:'move'}},1000),unstarted=client.request({spec:{type:'preview'}},5),cancelQueued=assert.rejects(unstarted,/キャンセル/);client.cancelPreviews();await cancelQueued;assert.equal(worker.messages.length,1);assert.ok(!worker.dead);worker.onmessage({data:{id:worker.messages[0].id,result:'moved'}});assert.equal(await ordinary,'moved');console.log('PASS factory recovery, active preview termination and queued preview-only cancellation');
