import assert from 'node:assert/strict';import {rgbaRaster,validateRaster,rasterRelief,rasterQualities,rasterImageDefaults,rasterResolution} from '../src/raster-relief.js';
const raster=rgbaRaster(4,2,new Uint8ClampedArray([0,0,0,255,85,85,85,255,170,170,170,255,255,255,255,255,0,0,0,255,85,85,85,255,170,170,170,255,255,255,255,255]));assert.deepEqual(raster.values,[0,85,170,255,0,85,170,255]);
const relief=rasterRelief(raster,{smoothing:0});for(const [i,value]of [0,1/3,2/3,1].entries())assert.ok(Math.abs(relief.sample((i+.5)/4,.5)-value)<1e-12);assert.ok(Math.abs(relief.sample(.5,.5)-.5)<1e-12,'gray makes a continuous intermediate height');
for(const seam of ['single','mirror','repeat']){assert.ok(Math.abs(relief.sample(0,.4,seam,3)-relief.sample(1,.4,seam,3))<1e-12);assert.ok(Math.abs(relief.sample(1e-8,.4,seam,3)-relief.sample(1-1e-8,.4,seam,3))<1e-6);}
assert.ok(Math.abs(relief.sample(.1,.4,'repeat',3)-relief.sample(.1+1/3,.4,'repeat',3))<1e-12);
const inverse=rasterRelief(raster,{invert:true,smoothing:0});for(let u=0;u<1;u+=.01)assert.ok(Math.abs(relief.sample(u,.5)+inverse.sample(u,.5)-1)<1e-12);
const transparent={...raster,alpha:[0,255,255,255,0,255,255,255]};assert.equal(rasterRelief(transparent,{invert:true,smoothing:2}).sample(.125,.5),0,'transparent pixel stays flat when inverted and smoothed');
const smooth=rasterRelief(raster,{smoothing:4});assert.ok(smooth.sample(.125,.5)>0&&smooth.sample(.875,.5)<1);for(const quality of Object.keys(rasterQualities))assert.ok(rasterRelief(raster,{quality}).columns>=48);
assert.deepEqual(rasterRelief(JSON.parse(JSON.stringify(raster)),relief.settings).values,relief.values);
for(const value of [{...raster,version:2},{...raster,width:513},{...raster,values:[0]},{...raster,values:raster.values.map(()=>NaN)},{...raster,alpha:[255]}])assert.throws(()=>validateRaster(value));
for(const settings of [{invert:1},{contrast:0},{contrast:NaN},{smoothing:1.5},{smoothing:5},{quality:'toString'}])assert.throws(()=>rasterRelief(raster,settings));
console.log('PASS grayscale levels, continuous interpolation, seamless repeats, invert/contrast/blur, transparency, save replay and invalid data');

const whiteBackground={version:1,width:32,height:32,values:Array.from({length:1024},(_,i)=>i%32>8&&i%32<24&&Math.floor(i/32)>6&&Math.floor(i/32)<26?20:255)};assert.deepEqual(rasterImageDefaults(whiteBackground),{invert:true,contrast:1.5,smoothing:0,quality:'standard'});assert.equal(rasterImageDefaults(raster).invert,false);assert.equal(rasterImageDefaults({...whiteBackground,alpha:whiteBackground.values.map(v=>v===255?0:255)}).invert,false);const one=rasterResolution(whiteBackground,{},'repeat',1),eight=rasterResolution(whiteBackground,{},'repeat',8);assert.equal(eight.segments/8,one.segments);assert.ok(eight.rows>=24);for(const count of [0,NaN,13,1.5])assert.throws(()=>rasterResolution(whiteBackground,{},'repeat',count));console.log('PASS white-background illustration defaults, transparency and equal detail per repeated image');
for(let count=1;count<=12;count++)assert.equal(rasterResolution({version:1,width:256,height:256,values:Array(65536).fill(128)},{quality:'fine'},'repeat',count).segments%count,0);console.log('PASS sampling budget preserves identical complete copies');

const fineSource={version:1,width:384,height:512,values:Array(384*512).fill(128)};const coarse=rasterResolution(fineSource,{quality:'standard'},'repeat',8),fine=rasterResolution(fineSource,{quality:'fine'},'repeat',8);assert.ok(fine.segments>coarse.segments&&fine.rows>coarse.rows,'fine adds detail in both directions at eight repeats');assert.equal(fine.segments/8,rasterResolution(fineSource,{quality:'fine'},'repeat',1).segments);assert.equal(fine.rows,rasterResolution(fineSource,{quality:'fine'},'repeat',1).rows);console.log('PASS high resolution source and independent fine detail in every repeated tile');
