import assert from 'node:assert/strict';
import {saveStl} from '../src/save-stl.js';
let generated=0,closed=false,aborted=false,written,options;
const data=new DataView(new ArrayBuffer(134));data.setUint32(80,1,true);
const create=()=>{generated++;return data;};
const unexpected=()=>assert.fail('Unexpected download');
globalThis.window={showSaveFilePicker:async value=>{options=value;return {createWritable:async()=>({write:async value=>{written=value;},close:async()=>{closed=true;}})};}};
assert.match(await saveStl(create,unexpected),/指定した場所/);
assert.equal(options.suggestedName,'design.stl');assert.deepEqual(options.types[0].accept,{'model/stl':['.stl']});assert.equal(written,data);assert.ok(closed);
const pickerOrder=[];
window.showSaveFilePicker=async()=>{pickerOrder.push('picker');return {createWritable:async()=>({write:async()=>{pickerOrder.push('write');},close:async()=>{pickerOrder.push('close');}})};};
await saveStl(async()=>{pickerOrder.push('validate');return data;},unexpected);
assert.deepEqual(pickerOrder,['picker','validate','write','close'],'picker runs during click activation before async validation');
window.showSaveFilePicker=async()=>{throw new DOMException('cancel','AbortError');};
assert.equal(await saveStl(create,unexpected),null);assert.equal(generated,1);
window.showSaveFilePicker=async()=>({createWritable:async()=>({write:async()=>{throw Error('disk full');},abort:async()=>{aborted=true;}})});
await assert.rejects(()=>saveStl(create,unexpected),/disk full/);assert.ok(aborted);
window={prompt:()=> '部品'};
let downloaded;await saveStl(create,(...args)=>{downloaded=args;});assert.equal(downloaded[1],'部品.stl');
const order=[];
window.prompt=()=>{order.push('prompt');return 'async';};
await saveStl(async()=>{order.push('validate');return data;},()=>{order.push('download');});
assert.deepEqual(order,['prompt','validate','download'],'filename prompt keeps user activation before async validation');
window.prompt=()=>null;assert.equal(await saveStl(create,unexpected),null);
console.log('PASS picker options, binary write/close, cancel, write failure and fallback filename');
