import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';
import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {makeSlideLid} from '../src/slide-lid.js';import {createSlideSectionModel} from '../src/slide-lid-section.js';import {runOperation} from '../src/kernel.js';import {defaults,validateProject} from '../src/geometry.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const p={lidStyle:'top',wall:4.2,floor:2.4,lidThickness:3.6,railDepth:1.2,cover:1.2,clearance:.25,direction:'long',entry:'negative',pose:'assembled',grip:true,lock:true,lockHeight:.35,divider:true,dividerCompartments:3,dividerDirection:'short',dividerThickness:2.4,filletInside:true,innerFilletRadius:1,filletOutside:true,outerFilletRadius:1};
const bounds=s=>{const b=s.boundingBox;try{return b.bounds;}finally{b.delete();}};function valid(s){const c=new (R.getOC().BRepCheck_Analyzer)(s.wrapped,true,false),solids=s.solids;try{assert.ok(c.IsValid());assert.equal(solids.length,1);}finally{c.delete();solids.forEach(s=>s.delete());}}
const hit=(s,point)=>{const b=R.makeBox(point.map(v=>v-.01),point.map(v=>v+.01)),a=s.intersect(b);try{return R.measureVolume(a);}finally{a.delete();b.delete();}};
const envelope=data=>data.parts.map(p=>p.fill.length?[Math.min(...p.fill.map(p=>p[0])),Math.min(...p.fill.map(p=>p[1])),Math.max(...p.fill.map(p=>p[0])),Math.max(...p.fill.map(p=>p[1]))]:[]);
for(const direction of ['long','short'])for(const entry of ['negative','positive'])for(const angle of [0,27]){
 const source=R.makeBox([-40,-25,3],[40,25,33]).rotate(angle,[0,0,0],[0,0,1]).translate([12,-7,0]),input={...p,direction,entry},result=makeSlideLid(source,input),printed=makeSlideLid(source,{...input,pose:'print'}),q=result.analysis;
 const world=(x,y,z)=>[q.center[0]+Math.cos(q.angle*Math.PI/180)*x-Math.sin(q.angle*Math.PI/180)*y,q.center[1]+Math.sin(q.angle*Math.PI/180)*x+Math.cos(q.angle*Math.PI/180)*y,q.center[2]+z];
 const mesh=r=>({outputs:[r.body.mesh({tolerance:.08,angularTolerance:.15}),r.lid.mesh({tolerance:.08,angularTolerance:.15})],analysis:r.analysis}),a=createSlideSectionModel(mesh(result),input),b=createSlideSectionModel(mesh(printed),{...input,pose:'print'});
 try{valid(result.body);valid(result.lid);valid(printed.lid);assert.equal(q.lidStyle,'top');assert.equal(q.overlap,0);assert.equal(q.slidingOverlap,0);assert.ok(q.lock.slidingContact>0);assert.equal(q.printFlipped,true);assert.ok(q.railStemWidth>=1.2);assert.ok(Math.abs(bounds(result.lid)[1][2]-33)<1e-6,'total original height preserved');assert.ok(Math.abs(bounds(printed.lid)[0][2])<1e-6);assert.ok(Math.abs(bounds(printed.body)[0][2])<1e-6);
  for(const x of [-q.length/2+.1,0,q.length/2-.1])for(const y of [-q.width/2+.1,0,q.width/2-.1])assert.ok(hit(result.lid,world(x,y,q.capLower+p.lidThickness/2))>1e-6,'cap covers the entire original top');assert.equal(hit(result.lid,world(0,0,q.grooveLower+.5)),0,'middle of old inset plate is absent');assert.ok(q.frontClosure.thickness>=1.2);for(const y of [0,-q.width/2+.1,q.width/2-.1])for(const z of [q.grooveLower+p.clearance+.5,q.capLower-.2])assert.ok(hit(result.lid,world(-q.length/2+.1,y,z))>1e-6,'front wall closes the entrance across the width and height');assert.equal(hit(result.lid,world(q.frontClosure.back+.5,0,q.capLower-.5)),0,'closure stays at the entrance and leaves the cavity open');assert.ok(hit(result.lid,world(0,q.width/2-p.wall-p.clearance-q.railStemWidth/2,q.capLower-.5))>1e-6,'underside stems attach rails to cap');
  for(const shift of [.7,-.7]){const lifted=result.lid.clone().translate([0,0,shift]),intersection=result.body.intersect(lifted);try{assert.ok(R.measureVolume(intersection)>0,'groove retains underside ridges vertically');}finally{lifted.delete();intersection.delete();}}
  const stopped=result.lid.clone().translate(q.axis.map(v=>v)),rear=result.body.intersect(stopped);try{assert.ok(R.measureVolume(rear)>0,'rail ends stop on rear wall');}finally{stopped.delete();rear.delete();}
  for(const focus of ['rail','lock','all'])for(const percent of [0,50,100]){const av=a.slice(focus,percent),bv=b.slice(focus,percent),ea=envelope(av),eb=envelope(bv);for(let i=0;i<ea.length;i++)for(let j=0;j<ea[i].length;j++)assert.ok(Math.abs(ea[i][j]-eb[i][j])<2e-4,'flipped print pose recovers same section');if(!percent)assert.equal(av.contact.area,0);}assert.ok(a.slice('lock',.85/q.openTravel*100).contact.area>1e-5);assert.equal(a.slice('rail',100).parts[1].segments.length,0);
  console.log('PASS full top cap, underside ridges, closed/slide clearance, retention, detent, fillets/dividers and print flip: '+direction+' / '+entry+' / '+angle);
 }finally{a.dispose();b.dispose();result.body.delete();result.lid.delete();printed.body.delete();printed.lid.delete();source.delete();}
}
const source=R.makeBox([-40,-25,0],[40,25,30]);try{for(const bad of [{lidStyle:'bad'},{lidThickness:25},{railDepth:10}])assert.throws(()=>makeSlideLid(source,{...p,...bad}));const thin=makeSlideLid(source,{...p,lidThickness:1.2});try{valid(thin.lid);assert.equal(thin.analysis.grip,null);}finally{thin.body.delete();thin.lid.delete();}}finally{source.delete();}
const base={...defaults,id:'box',kind:'extrusion',name:'直方体',width:80,height:50,depth:30,z:3},spec={...p,type:'slideLid',id:'slide',target:'box',pose:'print'},result=runOperation([base],spec),op={kind:'cadop',id:'slide',name:'スライド蓋',spec,...result},layoutSpec={type:'printLayout',id:'plate',targets:['box','slide-lid'],margin:2,gap:3,allowRotation:true},layout=runOperation([base,op],layoutSpec),before=[base,op,{kind:'cadop',id:'plate',name:'印刷配置',spec:layoutSpec,...layout}],next=structuredClone(before);next[1].spec.lidThickness=2.4;const replay=runOperation(next,{type:'replay',before,start:1});assert.equal(replay.features[1].analysis.lidStyle,'top');assert.equal(replay.features[1].analysis.lidThickness,2.4);validateProject({format:'forma-cad',version:1,features:replay.features});console.log('PASS invalid settings, thin cap, saved cap dimensions and replay through print layout');
