import {chromium} from 'playwright';import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
const page=await browser.newPage({viewport:{width:1500,height:1100},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:5188');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('閉じた'));await page.locator('#clear').click();
const approx=(a,b,label,tol=1e-8)=>{if(Math.abs(a-b)>tol)throw Error(label+': '+a+' != '+b)};
async function saved(){const p=page.waitForEvent('download');await page.locator('#save').click();const d=await p;return JSON.parse(await fs.readFile(await d.path(),'utf8')).features;}
async function screen(u,v,originU=0,originV=0){const b=await page.locator('canvas').boundingBox();const scale=b.height/(360*Math.tan(Math.PI/9));return {x:b.x+b.width/2+(u-originU)*scale,y:b.y+b.height/2-(v-originV)*scale};}
async function clickPoint(u,v,ou=0,ov=0){const p=await screen(u,v,ou,ov);await page.mouse.click(p.x,p.y);}
async function movePoint(u,v,ou=0,ov=0){const p=await screen(u,v,ou,ov);await page.mouse.move(p.x,p.y);}
for(const plane of ['XY','XZ','YZ']){
 await page.locator('#new-line').click();await page.locator('#plane').selectOption(plane);await page.locator('#x').fill('13');await page.locator('#y').fill('7');await page.locator('#z').fill('17');await page.locator('#snap-step').selectOption('10');await page.locator('#draw').click();await page.locator('#continuous-line').uncheck();
 const [ou,ov]=plane==='XY'?[13,7]:plane==='XZ'?[13,-17]:[-17,7];
 await movePoint(21.8,9.3,ou,ov);await clickPoint(21.8,9.3,ou,ov);await movePoint(61.2,39.1,ou,ov);await clickPoint(61.2,39.1,ou,ov);await page.locator('#apply').click();
 const f=(await saved()).at(-1);const a=f.angle*Math.PI/180;let u,v; if(plane==='XY'){u=f.x;v=f.y;approx(f.z,17,'normal XY');}else if(plane==='XZ'){u=f.x;v=-f.z;approx(f.y,7,'normal XZ');}else{u=-f.z;v=f.y;approx(f.x,13,'normal YZ');}
 approx(u-f.width/2*Math.cos(a),20,'snapped start u');approx(v-f.width/2*Math.sin(a),10,'snapped start v');approx(u+f.width/2*Math.cos(a),60,'snapped end u');approx(v+f.width/2*Math.sin(a),40,'snapped end v');approx(f.width,50,'diagonal length');
}
await page.locator('#clear').click();await page.locator('#new-line').click();await page.locator('#plane').selectOption('XY');await page.locator('#draw').click();await page.locator('#continuous-line').uncheck();await clickPoint(20,10);await page.locator('#live-length').fill('37.125');await page.locator('#live-angle').fill('30');await movePoint(70,-20);approx(Number(await page.locator('#width').inputValue()),37.125,'locked length');approx(Number(await page.locator('#angle').inputValue()),30,'locked angle');await page.locator('#live-angle').press('Enter');if(await page.locator('#line-dimensions').isVisible())throw Error('Enter did not place line');await page.locator('#apply').click();let f=(await saved()).at(-1);approx(f.width,37.125,'saved numeric length');approx(f.angle,30,'saved numeric angle');approx(f.x-f.width/2*Math.cos(Math.PI/6),20,'numeric anchored start');
await clickPoint(20+37.125*Math.cos(Math.PI/6)/2,10+37.125*Math.sin(Math.PI/6)/2);if(!(await page.locator('#measurement-length').textContent()).includes('37.125'))throw Error('Click measurement missing');if(!(await page.locator('#measurement-angle').textContent()).includes('30'))throw Error('Click angle missing');await page.screenshot({path:'.sites-runtime/measurement.png'});
await page.locator('#new-line').click();await page.locator('#snap-step').selectOption('5');await page.locator('#draw').click();await page.locator('#continuous-line').uncheck();await clickPoint(21,11);await movePoint(44,26);await page.screenshot({path:'.sites-runtime/dimensions.png'});await clickPoint(44,26);await page.locator('#apply').click();f=(await saved()).at(-1);approx(f.x,32.5,'5mm center x');approx(f.y,17.5,'5mm center y');
await page.locator('#new-line').click();await page.locator('#snap-enabled').uncheck();await page.locator('#draw').click();await page.locator('#continuous-line').uncheck();await clickPoint(21.3,11.7);await movePoint(43.2,25.8);await clickPoint(43.2,25.8);await page.locator('#apply').click();f=(await saved()).at(-1);if(Math.abs(f.x/5-Math.round(f.x/5))<.01)throw Error('Snap-off still snapped');
await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');if(errors.length)throw Error(errors.join('\n'));console.log('PASS: XY/XZ/YZ world grid snapping, offset planes, 5mm grid, snap toggle, fixed 37.125mm/30deg, Enter, saved line click measurement, mobile');
}finally{await browser.close();}
