import init from '../node_modules/replicad-opencascadejs/dist/replicad_single.js';
import * as R from 'replicad';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {runOperation} from '../src/kernel.js';import {defaults,validateProject} from '../src/geometry.js';
R.setOC(await init({wasmBinary:await fs.readFile('node_modules/replicad-opencascadejs/dist/replicad_single.wasm')}));
const params={bodyWall:4.2,lidWall:2.4,floor:2.4,insertion:4,clearance:.2,ridge:.4,pose:'assembled'};
for(const profile of ['rect','circle']){
const original={...defaults,id:'base',kind:'extrusion',name:'本体',profile,width:80,height:50,diameter:60,depth:40,x:10,y:-5,z:3};const cut=runOperation([original],{type:'split',id:'upper',target:'base',plane:'XY',offset:30}),split={kind:'cadop',id:'upper',name:'断面で分離',spec:{type:'split',id:'upper',target:'base',plane:'XY',offset:30},...cut},history=[original,split],spec={...params,type:'snapLid',id:'closure',target:'base',lidTarget:'upper'};
for(const pose of ['assembled','print']){const result=runOperation(history,{...spec,pose});assert.equal(result.outputs.length,2);assert.ok(result.analysis.overlap<1e-5);assert.ok(result.analysis.neckWall>=1.2);const bodies=result.outputs.map(o=>R.deserializeShape(o.brep).asShape3D());try{for(const b of bodies){const check=new (R.getOC().BRepCheck_Analyzer)(b.wrapped,true,false);assert.ok(check.IsValid());check.delete();assert.equal(b.solids.length,1);}const common=bodies[0].intersect(bodies[1]);assert.ok(R.measureVolume(common)<1e-5);common.delete();if(pose==='print')for(const o of result.outputs)assert.ok(Math.abs(Math.min(...o.vertices.filter((_,i)=>i%3===2)))<.0001);else{const probe=R.makeBox([8,-7,10],[12,-3,11]);const hole=bodies[0].intersect(probe);assert.ok(R.measureVolume(hole)<1e-8);hole.delete();probe.delete();assert.ok(Math.abs(Math.max(...result.outputs[0].vertices.filter((_,i)=>i%3===2))-34)<.001);const outer=profile==='rect'?50:40;const probeAt=(shape,x,z)=>{const p=R.makeBox([x,-5.1,z],[x+.03,-4.9,z+.01]),hit=shape.intersect(p);try{return R.measureVolume(hit);}finally{hit.delete();p.delete();}};assert.ok(probeAt(bodies[0],outer-2.32,32)>.00001,'retaining ridge projects past the bare neck');assert.ok(probeAt(bodies[0],outer-2.32,33)<1e-8,'ridge is confined to one height');assert.ok(probeAt(bodies[1],outer-2.32,32)<1e-8,'matching groove is open');assert.ok(probeAt(bodies[1],outer-2.32,33)>.00001,'lid wall remains beyond the groove');}validateProject({format:'forma-cad',version:1,features:[...history,{kind:'cadop',id:'closure',name:'被せ蓋',spec:{...spec,pose},...result}]});}finally{bodies.forEach(b=>b.delete());}console.log('PASS '+profile+' '+pose+' two valid shells, neck/groove, zero closed interference and print placement');}
for(const bad of [{bodyWall:2},{lidWall:1},{floor:30},{insertion:12},{ridge:2},{lidTarget:'base'},{clearance:.5},{insertion:1.5},{pose:'invalid'}])assert.throws(()=>runOperation(history,{...spec,...bad}));
}
