import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1550,height:1100},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:5188');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('閉じた'));
 const coord=async(u,v)=>{const b=await page.locator('canvas').boundingBox(),scale=b.height/(360*Math.tan(Math.PI/9));return {x:b.x+b.width/2+u*scale,y:b.y+b.height/2-v*scale};};
 const click=async(u,v)=>{const p=await coord(u,v);await page.mouse.move(p.x,p.y);await page.mouse.click(p.x,p.y);};
 async function save(){const p=page.waitForEvent('download');await page.locator('#save').click();return JSON.parse(await fs.readFile(await(await p).path(),'utf8'));}
 await page.locator('#new-line').click();await click(20,0);await click(70,0);assert.equal(await page.locator('#sketch-count').textContent(),'1');assert.equal(await page.locator('#line-dimensions').isVisible(),true);await click(70,40);await click(20,40);await click(20,0);assert.equal(await page.locator('#sketch-count').textContent(),'4');assert.equal(await page.locator('#region-count').textContent(),'1');assert.equal(await page.locator('#line-dimensions').isVisible(),false);assert.equal(await page.locator('#body-count').textContent(),'0');
 await page.locator('#finish-sketch-tool').click();await click(45,20);assert.match(await page.locator('#measurement-length').textContent(),/2,000/);await page.screenshot({path:'.sites-runtime/closed-profile.png'});await page.keyboard.press('e');await page.locator('#depth').fill('12');await page.locator('#apply').click();assert.equal(await page.locator('#body-count').textContent(),'1');let data=await save();assert.equal(data.features.at(-1).profile,'region');assert.equal(data.features.at(-1).region.area,2000);assert.equal(data.features.at(-1).depth,12);
 // Persisted region geometry must load and remain editable.
 await page.locator('#file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForTimeout(100);assert.equal(await page.locator('#body-count').textContent(),'1');await page.locator('#features .row-label').last().click();await page.locator('#depth').fill('8');await page.locator('#apply').click();assert.equal((await save()).features.at(-1).depth,8);
 // Open chain: Esc ends the line command without creating a final phantom segment.
 await page.locator('#clear').click();await page.keyboard.press('l');await click(20,0);await click(50,0);await click(50,20);await page.keyboard.press('Escape');assert.equal(await page.locator('#sketch-count').textContent(),'2');assert.equal(await page.locator('#region-count').textContent(),'0');await page.locator('#finish-sketch-tool').click();await page.locator('#solid-tool').click();assert.equal(await page.locator('#depth').isVisible(),false);assert.equal(await page.locator('#body-count').textContent(),'0');
 // Thin extrusion can still use an open line.
 await page.locator('#thin-tool').click();await click(35,0);assert.equal(await page.locator('#wall').isVisible(),true);await page.locator('#wall').fill('2');await page.locator('#apply').click();assert.equal(await page.locator('#body-count').textContent(),'1');
 // Numeric endpoints off grid are usable as the start/end of subsequent lines.
 await page.locator('#clear').click();await page.locator('#new-line').click();await click(20,0);await page.locator('#live-length').fill('23.125');await page.locator('#live-angle').fill('27');await page.locator('#live-angle').press('Enter');assert.equal(await page.locator('#sketch-count').textContent(),'1');assert.equal(await page.locator('#line-dimensions').isVisible(),true);await page.keyboard.press('Escape');const old=(await save()).features[0];await page.locator('#new-line').click();const endpoint=[old.x+old.width/2*Math.cos(old.angle*Math.PI/180),old.y+old.width/2*Math.sin(old.angle*Math.PI/180)];await click(...endpoint);await click(70,40);await page.keyboard.press('Escape');const next=(await save()).features[1];const start=[next.x-next.width/2*Math.cos(next.angle*Math.PI/180),next.y-next.width/2*Math.sin(next.angle*Math.PI/180)];assert.ok(Math.hypot(start[0]-endpoint[0],start[1]-endpoint[1])<1e-5);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: continuous loop, closed region selection/extrusion, saved region edit, open rejection, open thin, numeric endpoint snap, mobile');
}finally{await browser.close();}
